CREATE TABLE ADRESSE_BENEFICIAIRE (
  ID_ADRESSE_BENEFICIAIRE INTEGER NOT NULL,
  VOIE INTEGER NULL,
  NUMERO INTEGER NULL,
  COMPLEMENT_ADDR INTEGER NULL,
  VILLE INTEGER NULL,
  CODE_POSTAL INTEGER NULL
  );

CREATE TABLE ADRESSE_LIVRAISON (
  ID_ADRESSE_LIVRAISON INTEGER NOT NULL,
  DESTINATAIRE TEXT NOT NULL,
  NO_VOIE INTEGER NULL,
  VOIE TEXT NULL,
  COMPLEMENT TEXT NULL,
  CODE_POSTAL TEXT NULL,
  VILLE TEXT NULL
  );

CREATE TABLE APPLICATION (
  ID_APPLICATION INTEGER NOT NULL,
  CODE_APPLICATION TEXT NOT NULL,
  LIBELLE_APPLICATION TEXT NOT NULL
  );

CREATE TABLE AXE_CENTRAL (
  ID_AXE_CENTRAL INTEGER NOT NULL,
  CODE_AXE_CENTRAL TEXT NULL,
  LIBELLE_LONG_AXE_CENTRAL TEXT NULL,
  LIBELLE_COURT_AXE_CENTRAL TEXT NULL,
  STATUT TEXT NULL
  );

CREATE TABLE AXE_CENTRAL_BUGL (
  ID_BUGL INTEGER NOT NULL,
  ID_AXE_CENTRAL INTEGER NOT NULL,
  FOREIGN KEY (ID_BUGL) REFERENCES BUGL(ID_BUGL),
  FOREIGN KEY (ID_AXE_CENTRAL) REFERENCES AXE_CENTRAL(ID_AXE_CENTRAL)
  );

CREATE TABLE AXE_LOCAL (
  ID_AXE_LOCAL INTEGER NOT NULL,
  CODE_AXE_LOCAL TEXT NULL,
  LIBELLE_LONG_AXE_LOCAL TEXT NULL,
  LIBELLE_COURT_AXE_LOCAL TEXT NULL,
  STATUT TEXT NULL
  );

CREATE TABLE AXE_LOCAL_BUGL (
  ID_BUGL INTEGER NOT NULL,
  ID_AXE_LOCAL INTEGER NOT NULL,
  FOREIGN KEY (ID_BUGL) REFERENCES BUGL(ID_BUGL),
  FOREIGN KEY (ID_AXE_LOCAL) REFERENCES AXE_LOCAL(ID_AXE_LOCAL)
  );

CREATE TABLE BENEFICIAIRE (
  ID_BENEFICIAIRE INTEGER NOT NULL,
  ID_BENEFICIAIRE_PHYSIQUE INTEGER NULL,
  ID_BENEFICIAIRE_MORAL INTEGER NULL,
  ID_ADRESSE_BENEFICIAIRE INTEGER NULL,
  ID_SUSPENSION_BNF INTEGER NULL,
  CONSOMMATION_VOYAGES INTEGER NULL,
  DATE_CREATION REAL NULL,
  EN_PRE_CREATION BIT NOT NULL,
  EST_MORAL BIT NOT NULL,
  EST_EN_LISTE_NOIRE BIT NOT NULL,
  NB_CARTES_PVC_DELIVREES INTEGER NULL,
  ID_CLASSE_VOITURE INTEGER NULL,
  FOREIGN KEY (ID_ADRESSE_BENEFICIAIRE) REFERENCES ADRESSE_BENEFICIAIRE(ID_ADRESSE_BENEFICIAIRE),
  FOREIGN KEY (ID_BENEFICIAIRE_MORAL) REFERENCES BENEFICIAIRE_MORAL(ID_BENEFICIAIRE_MORAL),
  FOREIGN KEY (ID_BENEFICIAIRE_PHYSIQUE) REFERENCES BENEFICIAIRE_PHYSIQUE(ID_BENEFICIAIRE_PHYSIQUE),
  FOREIGN KEY (ID_CLASSE_VOITURE) REFERENCES CLASSE_VOITURE(ID_CLASSE_VOITURE),
  FOREIGN KEY (ID_SUSPENSION_BNF) REFERENCES SUSPENSION_BNF(ID_SUSPENSION_BNF)
  );

CREATE TABLE BENEFICIAIRE_DEMANDE (
  ID_BENEFICIAIRE_DEMANDE INTEGER NOT NULL,
  ID_DEMANDE INTEGER NOT NULL,
  ID_BENEFICIAIRE INTEGER NOT NULL,
  NOMBRE_EXEMPLAIRE INTEGER NULL,
  FOREIGN KEY (ID_BENEFICIAIRE) REFERENCES BENEFICIAIRE(ID_BENEFICIAIRE),
  FOREIGN KEY (ID_DEMANDE) REFERENCES DEMANDE(ID_DEMANDE)
  );

CREATE TABLE BENEFICIAIRE_DOSSIER_DELIVRANCE (
  ID_DOSSIER_DELIVRANCE INTEGER NOT NULL,
  ID_BENEFICIAIRE INTEGER NOT NULL,
  FOREIGN KEY (ID_DOSSIER_DELIVRANCE) REFERENCES DOSSIER_DELIVRANCE(ID_DOSSIER_DELIVRANCE),
  FOREIGN KEY (ID_BENEFICIAIRE) REFERENCES BENEFICIAIRE(ID_BENEFICIAIRE)
  );

CREATE TABLE BENEFICIAIRE_MORAL (
  ID_BENEFICIAIRE_MORAL INTEGER NOT NULL,
  NOM TEXT NOT NULL,
  OBSERVATION TEXT NULL,
  EMAIL INTEGER NULL
  );

CREATE TABLE BENEFICIAIRE_PHYSIQUE (
  ID_BENEFICIAIRE_PHYSIQUE INTEGER NOT NULL,
  ID_SITUATION_FAMILIALE INTEGER NULL,
  ID_CIVILITE INTEGER NULL,
  CODE_IMMATRICULATION TEXT NULL,
  OBSERVATION TEXT NULL,
  DATE_DECES REAL NULL,
  EST_HANDICAPE BIT NULL,
  MISSION TEXT NULL,
  NOM INTEGER NULL,
  PRENOM INTEGER NULL,
  DATE_NAISSANCE INTEGER NULL,
  LIEU_NAISSANCE INTEGER NULL,
  IMMAT_VEHICULE INTEGER NULL,
  TEL_MOBILE INTEGER NULL,
  EMAIL INTEGER NULL,
  EST_CLIENT_T BIT NOT NULL,
  EN_ACTIVITE BIT NULL,
  FOREIGN KEY (ID_CIVILITE) REFERENCES CIVILITE(ID_CIVILITE),
  FOREIGN KEY (ID_SITUATION_FAMILIALE) REFERENCES SITUATION_FAMILIALE(ID_SITUATION_FAMILIALE)
  );

CREATE TABLE BENEFICIARE_A_EXCLURE (
  ID_BENEFICIAIRE INTEGER NULL
  );

CREATE TABLE BENEFICIARE_PHYSIQUE_ROW_TMP (
  ID_BENEFICIAIRE_PHYSIQUE INTEGER NULL,
  ROWNUMBER INTEGER NULL
  );

CREATE TABLE BNF_TRAITE_CAMPAGNE (
  ID_BNF_TRAITE_CAMPAGNE INTEGER NOT NULL,
  ID_TYPE_CAMPAGNE INTEGER NOT NULL,
  ID_BENEFICIAIRE INTEGER NOT NULL,
  MILLESIME TEXT NULL,
  FOREIGN KEY (ID_BENEFICIAIRE) REFERENCES BENEFICIAIRE(ID_BENEFICIAIRE),
  FOREIGN KEY (ID_TYPE_CAMPAGNE) REFERENCES TYPE_CAMPAGNE(ID_TYPE_CAMPAGNE)
  );

CREATE TABLE BUGL (
  ID_BUGL INTEGER NOT NULL,
  CODE_BUGL TEXT NULL,
  LIBELLE_LONG_BUGL TEXT NULL,
  LIBELLE_COURT_BUGL TEXT NULL,
  STATUT TEXT NULL
  );

CREATE TABLE CARTE_TECHNIQUE (
  ID_CARTE_TECHNIQUE INTEGER NOT NULL,
  ID_FACILITE INTEGER NULL,
  NUMERO_TECHNIQUE_CARTE TEXT NOT NULL,
  NOMBRE_CARTES_PROD TEXT NOT NULL,
  DATE_PRODUCTION_CARTE REAL NOT NULL,
  FOREIGN KEY (ID_FACILITE) REFERENCES FACILITE(ID_FACILITE)
  );

CREATE TABLE CATEGORIE_BENEFICIAIRE (
  ID_CATEGORIE_BENEFICIAIRE INTEGER NOT NULL,
  ID_RESPONSABILITE_GESTION_DEFAUT_RNVLMT INTEGER NULL,
  ID_SUPPORT_OPERATION_DEFAUT_RNVLMT INTEGER NULL,
  ID_BUGLDEFAUT_RNVLMT INTEGER NULL,
  ID_AXE_LOCAL_DEFAUT_RNVLMT INTEGER NULL,
  ID_AXE_CENTRAL_DEFAUT_RNVLMT INTEGER NULL,
  ID_DEPARTEMENT_DEFAUT_RNVLMT INTEGER NULL,
  CODE_CATEGORIE_BENEFICIAIRE TEXT NULL,
  LIBELLE_CATEGORIE_BENEFICIAIRE TEXT NOT NULL,
  POURCENTAGE_REDUCTION_CONVENTIONNELLE INTEGER NULL,
  FOREIGN KEY (ID_AXE_CENTRAL_DEFAUT_RNVLMT) REFERENCES AXE_CENTRAL(ID_AXE_CENTRAL),
  FOREIGN KEY (ID_AXE_LOCAL_DEFAUT_RNVLMT) REFERENCES AXE_LOCAL(ID_AXE_LOCAL),
  FOREIGN KEY (ID_BUGLDEFAUT_RNVLMT) REFERENCES BUGL(ID_BUGL),
  FOREIGN KEY (ID_DEPARTEMENT_DEFAUT_RNVLMT) REFERENCES DEPARTEMENT(ID_DEPARTEMENT),
  FOREIGN KEY (ID_RESPONSABILITE_GESTION_DEFAUT_RNVLMT) REFERENCES RESPONSABILITE_GESTION(ID_RESPONSABILITE_GESTION),
  FOREIGN KEY (ID_SUPPORT_OPERATION_DEFAUT_RNVLMT) REFERENCES SUPPORT_OPERATION(ID_SUPPORT_OPERATION)
  );

CREATE TABLE CIVILITE (
  ID_CIVILITE INTEGER NOT NULL,
  CODE_CIVILITE TEXT NULL,
  LIBELLE_CIVILITE TEXT NOT NULL
  );

CREATE TABLE CLASSE_VOITURE (
  ID_CLASSE_VOITURE INTEGER NOT NULL,
  CODE_CLASSE_VOITURE TEXT NULL,
  LIBELLE_CLASSE_VOITURE TEXT NOT NULL
  );

CREATE TABLE CODE_FACILITE (
  ID_CODE_FACILITE INTEGER NOT NULL,
  ID_TYPE_FACILITE INTEGER NOT NULL,
  CODE_CODE_FACILITE TEXT NULL,
  LIBELLE_CODE_FACILITE TEXT NOT NULL,
  POURCENTAGE_REDUCTION INTEGER NULL,
  EST_SUPPRESSION_LOGIQUE BIT NOT NULL,
  EST_INIT BIT NOT NULL,
  ID_TYPE_VALORISATION INTEGER NOT NULL,
  FOREIGN KEY (ID_TYPE_FACILITE) REFERENCES TYPE_FACILITE(ID_TYPE_FACILITE),
  FOREIGN KEY (ID_TYPE_VALORISATION) REFERENCES TYPE_VALORISATION(ID_TYPE_VALORISATION)
  );

CREATE TABLE CODE_TARIF (
  ID_CODE_TARIF INTEGER NOT NULL,
  CODE_CODE_TARIF TEXT NULL,
  LIBELLE_CODE_TARIF TEXT NOT NULL,
  TYPE_PASSAGER TEXT NULL,
  EST_SUPPRESSION_LOGIQUE BIT NOT NULL,
  EST_CLIENT_T BIT NOT NULL
  );

CREATE TABLE CODE_TARIF_ECODE (
  ID_CODE_TARIF_ECODE INTEGER NOT NULL,
  CANAL_ECODE TEXT NOT NULL,
  PREFIX_ECODE TEXT NOT NULL,
  TYPE_CODE TEXT NOT NULL,
  TYPE_ID_ECODE INTEGER NOT NULL,
  MAIL_ID_ECODE INTEGER NOT NULL,
  MAIL_OBJET_ECODE TEXT NOT NULL,
  WSCREATION_TYPECODE TEXT NOT NULL,
  WSCREATION_ID_PROMOTION TEXT NOT NULL,
  WSCREATION_LIBELLE_PROMO_COURT TEXT NOT NULL,
  WSCREATION_LIBELLE_PROMO_LONG TEXT NOT NULL,
  WSCREATION_ORIGINE_EMISSION TEXT NOT NULL,
  WSCREATION_NATURE_COMPTABLE TEXT NOT NULL,
  WSCREATION_CODE_EMMETEUR TEXT NOT NULL,
  WSCREATION_TYPE_EMMETEUR TEXT NOT NULL,
  WSCREATION_NBCODES INTEGER NOT NULL,
  ID_CODE_TARIF INTEGER NOT NULL
  );

CREATE TABLE DELIVRER_FC_MASSE (
  ID_DELIVRER_FC_MASSE INTEGER NOT NULL,
  ID_DEMANDE INTEGER NULL,
  ID_RENOUVELLEMENT INTEGER NULL,
  ID_DOSSIER_DELIVRANCE INTEGER NOT NULL,
  NOM_FICHIER TEXT NULL,
  CHEMIN_FICHIER TEXT NULL,
  STATUT_TRAITEMENT TEXT NOT NULL,
  MESSAGE_ERREUR TEXT NULL,
  ADRESSE_MAIL TEXT NOT NULL,
  ID_UTILISATEUR INTEGER NOT NULL,
  DATE_CREATION REAL NOT NULL
  );

CREATE TABLE DEMANDE (
  ID_DEMANDE INTEGER NOT NULL,
  ID_SOUS_CATEGORIE_BENEFICIAIRE INTEGER NOT NULL,
  ID_ADRESSE_LIVRAISON INTEGER NULL,
  ID_AXE_LOCAL INTEGER NULL,
  ID_RESPONSABILITE_GESTION INTEGER NULL,
  ID_AXE_CENTRAL INTEGER NULL,
  ID_SUPPORT_OPERATION INTEGER NULL,
  ID_BUGL INTEGER NULL,
  ID_UTILISATEUR_AFFECTE INTEGER NULL,
  ID_UTILISATEUR_CREATEUR INTEGER NULL,
  ID_MOTIF_DEMANDE INTEGER NOT NULL,
  ID_TYPE_LIVRAISON INTEGER NOT NULL,
  ID_TYPE_DEMANDE INTEGER NOT NULL,
  ID_DEPARTEMENT INTEGER NULL,
  NO_DEMANDE TEXT NULL,
  DATE_DEMANDE REAL NULL,
  COMMENTAIRE TEXT NULL,
  DATE_CREATION REAL NOT NULL,
  EST_PRIORITAIRE BIT NOT NULL,
  ID_LIEU_AFFECTATION INTEGER NULL,
  URL_FICHIER_ERREUR_RATTACH_BENEF TEXT NULL,
  FOREIGN KEY (ID_ADRESSE_LIVRAISON) REFERENCES ADRESSE_LIVRAISON(ID_ADRESSE_LIVRAISON),
  FOREIGN KEY (ID_AXE_CENTRAL) REFERENCES AXE_CENTRAL(ID_AXE_CENTRAL),
  FOREIGN KEY (ID_AXE_LOCAL) REFERENCES AXE_LOCAL(ID_AXE_LOCAL),
  FOREIGN KEY (ID_BUGL) REFERENCES BUGL(ID_BUGL),
  FOREIGN KEY (ID_DEPARTEMENT) REFERENCES DEPARTEMENT(ID_DEPARTEMENT),
  FOREIGN KEY (ID_LIEU_AFFECTATION) REFERENCES LIEU_AFFECTATION(ID_LIEU_AFFECTATION),
  FOREIGN KEY (ID_MOTIF_DEMANDE) REFERENCES MOTIF_DEMANDE(ID_MOTIF_DEMANDE),
  FOREIGN KEY (ID_RESPONSABILITE_GESTION) REFERENCES RESPONSABILITE_GESTION(ID_RESPONSABILITE_GESTION),
  FOREIGN KEY (ID_SOUS_CATEGORIE_BENEFICIAIRE) REFERENCES SOUS_CATEGORIE_BENEFICIAIRE(ID_SOUS_CATEGORIE_BENEFICIAIRE),
  FOREIGN KEY (ID_SUPPORT_OPERATION) REFERENCES SUPPORT_OPERATION(ID_SUPPORT_OPERATION),
  FOREIGN KEY (ID_TYPE_DEMANDE) REFERENCES TYPE_DEMANDE(ID_TYPE_DEMANDE),
  FOREIGN KEY (ID_TYPE_LIVRAISON) REFERENCES TYPE_LIVRAISON(ID_TYPE_LIVRAISON),
  FOREIGN KEY (ID_UTILISATEUR_AFFECTE) REFERENCES UTILISATEUR(ID_UTILISATEUR),
  FOREIGN KEY (ID_UTILISATEUR_CREATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
  );

CREATE TABLE DEPARTEMENT (
  ID_DEPARTEMENT INTEGER NOT NULL,
  ID_RESPONSABILITE_GESTION INTEGER NOT NULL,
  CODE_DEPARTEMENT TEXT NULL,
  LIBELLE_LONG_DEPARTEMENT TEXT NULL,
  LIBELLE_COURT_DEPARTEMENT TEXT NULL,
  STATUT TEXT NULL,
  FOREIGN KEY (ID_RESPONSABILITE_GESTION) REFERENCES RESPONSABILITE_GESTION(ID_RESPONSABILITE_GESTION)
  );

CREATE TABLE DISTANCES_GP (
  ID_DISTANCES_GP INTEGER NOT NULL,
  ID_GARE_PRINCIPALE_ORIGINE INTEGER NOT NULL,
  ID_GARE_PRINCIPALE_DESTINATION INTEGER NOT NULL,
  DISTANCE INTEGER NULL,
  FOREIGN KEY (ID_GARE_PRINCIPALE_DESTINATION) REFERENCES GARE(ID_GARE),
  FOREIGN KEY (ID_GARE_PRINCIPALE_ORIGINE) REFERENCES GARE(ID_GARE)
  );

CREATE TABLE DISTANCES_GS (
  ID_DISTANCES_GS INTEGER NOT NULL,
  ID_GARE_SECONDAIRE INTEGER NOT NULL,
  ID_GARE_PRINCIPALE2 INTEGER NULL,
  ID_GARE_PRINCIPALE1 INTEGER NOT NULL,
  DISTANCE_GP1 INTEGER NULL,
  DISTANCE_GP2 INTEGER NULL,
  FOREIGN KEY (ID_GARE_PRINCIPALE2) REFERENCES GARE(ID_GARE),
  FOREIGN KEY (ID_GARE_PRINCIPALE1) REFERENCES GARE(ID_GARE),
  FOREIGN KEY (ID_GARE_SECONDAIRE) REFERENCES GARE(ID_GARE)
  );

CREATE TABLE DOSSIER_ARENOUVELER (
  ID_DOSSIER_ENCOURS_RENOUVELLEMENT INTEGER NOT NULL,
  ID_UTILISATEUR_AVEC_DOSSIER_ARENOUVELER INTEGER NOT NULL,
  FOREIGN KEY (ID_UTILISATEUR_AVEC_DOSSIER_ARENOUVELER) REFERENCES UTILISATEUR(ID_UTILISATEUR),
  FOREIGN KEY (ID_DOSSIER_ENCOURS_RENOUVELLEMENT) REFERENCES DOSSIER_DELIVRANCE(ID_DOSSIER_DELIVRANCE)
  );

CREATE TABLE DOSSIER_DELIVRANCE (
  ID_DOSSIER_DELIVRANCE INTEGER NOT NULL,
  ID_UTILISATEUR INTEGER NOT NULL,
  ID_DEMANDE INTEGER NULL,
  ID_MOTIF_DELIVRANCE INTEGER NULL,
  ID_CODE_FACILITE INTEGER NULL,
  ID_DEPARTEMENT INTEGER NULL,
  ID_RESPONSABILITE_GESTION INTEGER NULL,
  ID_AXE_LOCAL INTEGER NULL,
  ID_CODE_TARIF INTEGER NULL,
  ID_PROPOSITION_FCRNVLMT INTEGER NULL,
  ID_AXE_CENTRAL INTEGER NULL,
  ID_SUPPORT_OPERATION INTEGER NULL,
  ID_CLASSE_VOITURE INTEGER NULL,
  ID_BUGL INTEGER NULL,
  QUANTITE INTEGER NULL,
  MILLESIME TEXT NULL,
  LIBELLE_BENEFICIAIRE TEXT NULL,
  MENTION1 TEXT NULL,
  MENTION2 TEXT NULL,
  MENTION3 TEXT NULL,
  MENTION4 TEXT NULL,
  MENTION5 TEXT NULL,
  MENTION6 TEXT NULL,
  MENTION7 TEXT NULL,
  MENTION8 TEXT NULL,
  MENTION9 TEXT NULL,
  MENTION10 TEXT NULL,
  EST_VISIBLE_MISSION BIT NOT NULL,
  EST_VISIBLE_SOUS_CATEGORIE BIT NOT NULL,
  DATE_DELIVRANCE REAL NULL,
  LIBELLE_CODE_FACILITE TEXT NULL,
  LIBELLE_CODE_TARIF TEXT NULL,
  ID_TYPE_SUPPORT_PHYSIQUE INTEGER NULL,
  NBFC_ANNULEE INTEGER NULL,
  NB_ACCOMPAGNANTS INTEGER NULL,
  PHOTO BIT NULL,
  ID_TAMPON INTEGER NULL,
  DATE_DEBUT_VALIDITE_BROUILLON REAL NULL,
  DATE_FIN_VALIDITE_BROUILLON REAL NULL,
  NB_CASES INTEGER NULL,
  EST_EN_DEROGATION BIT NULL,
  NB_FC INTEGER NULL,
  EST_MILLESIME BIT NULL,
  IDF BIT NULL,
  FOREIGN KEY (ID_AXE_CENTRAL) REFERENCES AXE_CENTRAL(ID_AXE_CENTRAL),
  FOREIGN KEY (ID_AXE_LOCAL) REFERENCES AXE_LOCAL(ID_AXE_LOCAL),
  FOREIGN KEY (ID_BUGL) REFERENCES BUGL(ID_BUGL),
  FOREIGN KEY (ID_CLASSE_VOITURE) REFERENCES CLASSE_VOITURE(ID_CLASSE_VOITURE),
  FOREIGN KEY (ID_CODE_FACILITE) REFERENCES CODE_FACILITE(ID_CODE_FACILITE),
  FOREIGN KEY (ID_CODE_TARIF) REFERENCES CODE_TARIF(ID_CODE_TARIF),
  FOREIGN KEY (ID_DEMANDE) REFERENCES DEMANDE(ID_DEMANDE),
  FOREIGN KEY (ID_DEPARTEMENT) REFERENCES DEPARTEMENT(ID_DEPARTEMENT),
  FOREIGN KEY (ID_MOTIF_DELIVRANCE) REFERENCES MOTIF_DELIVRANCE(ID_MOTIF_DELIVRANCE),
  FOREIGN KEY (ID_PROPOSITION_FCRNVLMT) REFERENCES PROPOSITION_FCRNVLMT(ID_PROPOSITION_FCRNVLMT),
  FOREIGN KEY (ID_RESPONSABILITE_GESTION) REFERENCES RESPONSABILITE_GESTION(ID_RESPONSABILITE_GESTION),
  FOREIGN KEY (ID_SUPPORT_OPERATION) REFERENCES SUPPORT_OPERATION(ID_SUPPORT_OPERATION),
  FOREIGN KEY (ID_TYPE_SUPPORT_PHYSIQUE) REFERENCES TYPE_SUPPORT_PHYSIQUE(ID_TYPE_SUPPORT_PHYSIQUE),
  FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
  );

CREATE TABLE ERREUR_FICHIER (
  ID_ERREUR_FICHIER INTEGER NOT NULL,
  ID_TRAITEMENT_FICHIER INTEGER NOT NULL,
  ID_TYPE_ERREUR_FICHIER INTEGER NOT NULL,
  ID_GRAVITE_ERREUR INTEGER NOT NULL,
  NO_LIGNE INTEGER NULL,
  LIBELLE_ERREUR TEXT NULL,
  DETAIL_ERREUR TEXT NULL,
  DATE_ERREUR REAL NULL,
  FOREIGN KEY (ID_GRAVITE_ERREUR) REFERENCES GRAVITE_ERREUR(ID_GRAVITE_ERREUR),
  FOREIGN KEY (ID_TRAITEMENT_FICHIER) REFERENCES TRAITEMENT_FICHIER(ID_TRAITEMENT_FICHIER),
  FOREIGN KEY (ID_TYPE_ERREUR_FICHIER) REFERENCES TYPE_ERREUR_FICHIER(ID_TYPE_ERREUR_FICHIER)
  );

CREATE TABLE ERREUR_TACHE (
  ID_ERREUR_TACHE INTEGER NOT NULL,
  ID_EXECUTION_TACHE INTEGER NOT NULL,
  ID_TYPE_ERREUR_TACHE INTEGER NOT NULL,
  ID_GRAVITE_ERREUR INTEGER NOT NULL,
  LIBELLE_ERREUR TEXT NULL,
  DETAIL_ERREUR TEXT NULL,
  DATE_ERREUR REAL NOT NULL,
  FOREIGN KEY (ID_EXECUTION_TACHE) REFERENCES EXECUTION_TACHE(ID_EXECUTION_TACHE),
  FOREIGN KEY (ID_GRAVITE_ERREUR) REFERENCES GRAVITE_ERREUR(ID_GRAVITE_ERREUR),
  FOREIGN KEY (ID_TYPE_ERREUR_TACHE) REFERENCES TYPE_ERREUR_TACHE(ID_TYPE_ERREUR_TACHE)
  );

CREATE TABLE ETAT_FICHIER (
  ID_ETAT_FICHIER INTEGER NOT NULL,
  CODE_ETAT_FICHIER TEXT NULL,
  LIBELLE_ETAT_FICHIER TEXT NOT NULL
  );

CREATE TABLE ETAT_TACHE (
  ID_ETAT_TACHE INTEGER NOT NULL,
  CODE_ETAT_TACHE TEXT NULL,
  LIBELLE_ETAT_TACHE TEXT NOT NULL
  );

CREATE TABLE EVT_VALORISATION_GLOBAL (
  ID_EVT_VALORISATION_GLOBAL INTEGER NOT NULL,
  ID_TYPE_EVENEMENT INTEGER NOT NULL,
  DATE_EVENEMENT REAL NOT NULL,
  DATE_DEBUT_TRAITEMENT REAL NULL,
  DATE_FIN_TRAITEMENT REAL NULL,
  FOREIGN KEY (ID_TYPE_EVENEMENT) REFERENCES TYPE_EVENEMENT(ID_TYPE_EVENEMENT)
  );

CREATE TABLE EVT_VALORISATION_LOCAL (
  ID_EVT_VALORISATION_LOCAL INTEGER NOT NULL,
  ID_FACILITE INTEGER NOT NULL,
  ID_TYPE_EVENEMENT INTEGER NOT NULL,
  DATE_EVENEMENT REAL NOT NULL,
  DATE_DEBUT_TRAITEMENT REAL NULL,
  DATE_FIN_TRAITEMENT REAL NULL,
  FOREIGN KEY (ID_FACILITE) REFERENCES FACILITE(ID_FACILITE),
  FOREIGN KEY (ID_TYPE_EVENEMENT) REFERENCES TYPE_EVENEMENT(ID_TYPE_EVENEMENT)
  );

CREATE TABLE EXECUTION_TACHE (
  ID_EXECUTION_TACHE INTEGER NOT NULL,
  ID_TACHE INTEGER NOT NULL,
  ID_ETAT_TACHE INTEGER NOT NULL,
  DATE_DEBUT_EXECUTION REAL NULL,
  DATE_FIN_EXECUTION REAL NULL,
  FOREIGN KEY (ID_ETAT_TACHE) REFERENCES ETAT_TACHE(ID_ETAT_TACHE),
  FOREIGN KEY (ID_TACHE) REFERENCES TACHE(ID_TACHE)
  );

CREATE TABLE FACILITE (
  ID_FACILITE INTEGER NOT NULL,
  ID_DOSSIER_DELIVRANCE INTEGER NOT NULL,
  ID_BENEFICIAIRE INTEGER NOT NULL,
  NUMERO_SUPPORT TEXT NULL,
  DATE_DELIVRANCE REAL NULL,
  DATE_DEBUT_VALIDITE REAL NULL,
  DATE_FIN_VALIDITE REAL NULL,
  EST_HISTORISEE BIT NOT NULL,
  EST_HORS_CONTINGENCE BIT NOT NULL,
  EST_INIT BIT NOT NULL,
  NB_CASES_DELIVREES INTEGER NULL,
  ID_PARCOURS_DEMANDE INTEGER NULL,
  ID_UTILISATEUR INTEGER NOT NULL,
  EST_PARCOURS_ALLER BIT NULL,
  NB_ESSAIS_CODE_SECRET INTEGER NULL,
  CODE_SECRET INTEGER NULL,
  EST_RATTRAPAGE BIT NOT NULL
  );

CREATE TABLE FACILITE_FACTUREE (
  ID_FACILITE_FACTUREE INTEGER NOT NULL,
  QUANTITE_PRODUITE INTEGER NOT NULL,
  VALEUR_UNITE_OEUVRE REAL NOT NULL,
  ORIGINE_FACTURE TEXT NOT NULL,
  ANNEE_FACTURE TEXT NOT NULL,
  MOIS_FACTURE TEXT NOT NULL,
  ID_AXE_CENTRAL_CLIENT INTEGER NOT NULL,
  ID_AXE_CENTRAL_FOURNISSEUR INTEGER NOT NULL,
  ID_AXE_LOCAL_CLIENT INTEGER NULL,
  ID_SUPPORT_OPERATION_CLIENT INTEGER NULL,
  ID_SUPPORT_OPERATION_FOURNISSEUR INTEGER NOT NULL,
  ID_DEPARTEMENT_CLIENT INTEGER NULL,
  ID_RESPONSABILITE_GESTION_CLIENTE INTEGER NOT NULL,
  ID_FACILITE INTEGER NULL,
  FOREIGN KEY (ID_AXE_CENTRAL_CLIENT) REFERENCES AXE_CENTRAL(ID_AXE_CENTRAL),
  FOREIGN KEY (ID_AXE_CENTRAL_FOURNISSEUR) REFERENCES AXE_CENTRAL(ID_AXE_CENTRAL),
  FOREIGN KEY (ID_AXE_LOCAL_CLIENT) REFERENCES AXE_LOCAL(ID_AXE_LOCAL),
  FOREIGN KEY (ID_DEPARTEMENT_CLIENT) REFERENCES DEPARTEMENT(ID_DEPARTEMENT),
  FOREIGN KEY (ID_FACILITE) REFERENCES FACILITE(ID_FACILITE),
  FOREIGN KEY (ID_RESPONSABILITE_GESTION_CLIENTE) REFERENCES RESPONSABILITE_GESTION(ID_RESPONSABILITE_GESTION),
  FOREIGN KEY (ID_SUPPORT_OPERATION_CLIENT) REFERENCES SUPPORT_OPERATION(ID_SUPPORT_OPERATION),
  FOREIGN KEY (ID_SUPPORT_OPERATION_FOURNISSEUR) REFERENCES SUPPORT_OPERATION(ID_SUPPORT_OPERATION)
  );

CREATE TABLE FACILITE_VALORISEE (
  ID_FACILITE_VALORISEE INTEGER NOT NULL,
  ID_FACILITE INTEGER NOT NULL,
  ID_CODE_FACILITE INTEGER NOT NULL,
  ID_TYPE_TARIFICATION INTEGER NULL,
  ID_CODE_TARIF INTEGER NULL,
  MONTANT_VALORISE REAL NOT NULL,
  DATE_DEBUT_VALORISATION REAL NOT NULL,
  DATE_FIN_VALORISATION REAL NOT NULL,
  DATE_DELIVRANCE REAL NULL,
  NB_KILOMETRES INTEGER NULL,
  NB_PERSONNES NUMERIC(4, 1) NULL,
  NB_MOIS_VALORISATION INTEGER NOT NULL,
  DATE_MAJ REAL NULL,
  PRC INTEGER NULL,
  COEFFICIENT_A NUMERIC(9, 4) NULL,
  FOREIGN KEY (ID_CODE_FACILITE) REFERENCES CODE_FACILITE(ID_CODE_FACILITE),
  FOREIGN KEY (ID_CODE_TARIF) REFERENCES CODE_TARIF(ID_CODE_TARIF),
  FOREIGN KEY (ID_FACILITE) REFERENCES FACILITE(ID_FACILITE),
  FOREIGN KEY (ID_TYPE_TARIFICATION) REFERENCES TYPE_TARIFICATION(ID_TYPE_TARIFICATION)
  );

CREATE TABLE FC_REBUS (
  ID_FC_REBUS INTEGER NOT NULL,
  NUMERO_FC TEXT NULL,
  DATE_REBUS REAL NULL
  );

CREATE TABLE FC_REBUS_STOCK (
  ID_FC_REBUS INTEGER NOT NULL,
  ID_STOCK_SUPPORT_PHYSIQUE INTEGER NOT NULL,
  FOREIGN KEY (ID_STOCK_SUPPORT_PHYSIQUE) REFERENCES STOCK_SUPPORT_PHYSIQUE(ID_STOCK_SUPPORT_PHYSIQUE),
  FOREIGN KEY (ID_FC_REBUS) REFERENCES FC_REBUS(ID_FC_REBUS)
  );

CREATE TABLE FICHET (
  ID_FICHET INTEGER NOT NULL,
  NOMBRE_CASES INTEGER NULL,
  ID_DOSSIER_DELIVRANCE INTEGER NULL,
  FOREIGN KEY (ID_DOSSIER_DELIVRANCE) REFERENCES DOSSIER_DELIVRANCE(ID_DOSSIER_DELIVRANCE)
  );

CREATE TABLE FILIATION (
  ID_FILIATION INTEGER NOT NULL,
  ID_TYPE_FILIATION INTEGER NOT NULL,
  CODE_FILIATION TEXT NULL,
  LIBELLE_FILIATION TEXT NOT NULL,
  FOREIGN KEY (ID_TYPE_FILIATION) REFERENCES TYPE_FILIATION(ID_TYPE_FILIATION)
  );

CREATE TABLE GARE (
  ID_GARE INTEGER NOT NULL,
  ID_TYPE_GARE INTEGER NOT NULL,
  CODE_GARE TEXT NULL,
  LIBELLE_GARE TEXT NOT NULL,
  EST_SUPPRESSION_LOGIQUE BIT NULL,
  FOREIGN KEY (ID_TYPE_GARE) REFERENCES TYPE_GARE(ID_TYPE_GARE)
  );

CREATE TABLE GRAVITE_ERREUR (
  ID_GRAVITE_ERREUR INTEGER NOT NULL,
  CODE_GRAVITE_ERREUR TEXT NULL,
  LIBELLE_GRAVITE_ERREUR TEXT NOT NULL
  );

CREATE TABLE HISTORIQUE_AFFECTATION (
  ID_HISTORIQUE_AFFECTATION INTEGER NOT NULL,
  ID_DEMANDE INTEGER NOT NULL,
  ID_UTILISATEUR INTEGER NOT NULL,
  DATE_AFFECTATION_DEMANDE REAL NOT NULL,
  FOREIGN KEY (ID_DEMANDE) REFERENCES DEMANDE(ID_DEMANDE),
  FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
  );

CREATE TABLE HISTORIQUE_LISTE_NOIRE (
  ID_HISTORIQUE_LISTE_NOIRE INTEGER NOT NULL,
  ID_BENEFICIAIRE INTEGER NOT NULL,
  DATE_ENTREE_LISTE_NOIRE REAL NOT NULL,
  DATE_SORTIE_LISTE_NOIRE REAL NULL,
  LIBELLE_MOTIF_LISTE_NOIRE TEXT NOT NULL,
  FOREIGN KEY (ID_BENEFICIAIRE) REFERENCES BENEFICIAIRE(ID_BENEFICIAIRE)
  );

CREATE TABLE HISTORIQUE_STATUT_CARTE_APUCE (
  ID_HISTORIQUE_STATUT_CARTE_APUCE INTEGER NOT NULL,
  ID_MOTIF_STATUT INTEGER NULL,
  ID_STATUT_CARTE_APUCE INTEGER NOT NULL,
  ID_FACILITE INTEGER NOT NULL,
  DATE_STATUT REAL NOT NULL,
  LIBELLE_CANAL_DISTRIBUTION TEXT NULL,
  FOREIGN KEY (ID_FACILITE) REFERENCES FACILITE(ID_FACILITE),
  FOREIGN KEY (ID_MOTIF_STATUT) REFERENCES MOTIF_STATUT(ID_MOTIF_STATUT),
  FOREIGN KEY (ID_STATUT_CARTE_APUCE) REFERENCES STATUT_CARTE_APUCE(ID_STATUT_CARTE_APUCE)
  );

CREATE TABLE HISTORIQUE_STATUT_DEMANDE (
  ID_HISTORIQUE_STATUT_DEMANDE INTEGER NOT NULL,
  ID_DEMANDE INTEGER NOT NULL,
  ID_STATUT_DEMANDE INTEGER NOT NULL,
  DATE_STATUT_DEMANDE REAL NOT NULL,
  LIBELLE_MOTIF_STATUT_DEMANDE TEXT NULL,
  FOREIGN KEY (ID_DEMANDE) REFERENCES DEMANDE(ID_DEMANDE),
  FOREIGN KEY (ID_STATUT_DEMANDE) REFERENCES STATUT_DEMANDE(ID_STATUT_DEMANDE)
  );

CREATE TABLE HISTORIQUE_STATUT_FACILITE (
  ID_HISTORIQUE_STATUT_FACILITE INTEGER NOT NULL,
  ID_MOTIF_STATUT INTEGER NULL,
  ID_STATUT_FACILITE INTEGER NOT NULL,
  ID_FACILITE INTEGER NOT NULL,
  DATE_STATUT REAL NOT NULL,
  FOREIGN KEY (ID_FACILITE) REFERENCES FACILITE(ID_FACILITE),
  FOREIGN KEY (ID_MOTIF_STATUT) REFERENCES MOTIF_STATUT(ID_MOTIF_STATUT),
  FOREIGN KEY (ID_STATUT_FACILITE) REFERENCES STATUT_FACILITE(ID_STATUT_FACILITE)
  );

CREATE TABLE IMPUTATION_COMPTABLE_PAR_UTILISATEUR (
  ID_IMPUTATION_COMPTABLE_PAR_UTILISATEUR INTEGER NOT NULL,
  ID_SUPPORT_OPERATION INTEGER NULL,
  ID_BUGL INTEGER NULL,
  ID_RESPONSABILITE_GESTION INTEGER NULL,
  ID_UTILISATEUR INTEGER NULL,
  ID_AXE_CENTRAL INTEGER NULL,
  ID_AXE_LOCAL INTEGER NULL,
  ID_DEPARTEMENT INTEGER NULL,
  LIBELLE TEXT NULL,
  FOREIGN KEY (ID_AXE_CENTRAL) REFERENCES AXE_CENTRAL(ID_AXE_CENTRAL),
  FOREIGN KEY (ID_AXE_LOCAL) REFERENCES AXE_LOCAL(ID_AXE_LOCAL),
  FOREIGN KEY (ID_BUGL) REFERENCES BUGL(ID_BUGL),
  FOREIGN KEY (ID_DEPARTEMENT) REFERENCES DEPARTEMENT(ID_DEPARTEMENT),
  FOREIGN KEY (ID_RESPONSABILITE_GESTION) REFERENCES RESPONSABILITE_GESTION(ID_RESPONSABILITE_GESTION),
  FOREIGN KEY (ID_SUPPORT_OPERATION) REFERENCES SUPPORT_OPERATION(ID_SUPPORT_OPERATION),
  FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
  );

CREATE TABLE LIEU_AFFECTATION (
  ID_LIEU_AFFECTATION INTEGER NOT NULL,
  CODE_LIEU_AFFECTATION TEXT NULL,
  LIBELLE_LIEU_AFFECTATION TEXT NULL,
  ID_TYPE_LIEU_AFFECTATION INTEGER NOT NULL,
  VOIE TEXT NULL,
  COMPLEMENT_ADDR TEXT NULL,
  CODE_POSTAL TEXT NULL,
  VILLE TEXT NULL,
  PAYS TEXT NULL,
  FOREIGN KEY (ID_TYPE_LIEU_AFFECTATION) REFERENCES TYPE_LIEU_AFFECTATION(ID_TYPE_LIEU_AFFECTATION)
  );

CREATE TABLE LOT (
  ID_LOT INTEGER NOT NULL,
  DATE_CREATION_LOT REAL NOT NULL,
  DATE_RECEPTION_LOT REAL NULL,
  NUMERO_DEBUT TEXT NOT NULL,
  NUMERO_FIN TEXT NOT NULL,
  DATE_AFFECTATION_LOT REAL NULL,
  ID_STOCK_SUPPORT_PHYSIQUE_RECEPTEUR INTEGER NOT NULL,
  ID_STOCK_SUPPORT_PHYSIQUE_CREATEUR INTEGER NOT NULL,
  FOREIGN KEY (ID_STOCK_SUPPORT_PHYSIQUE_CREATEUR) REFERENCES STOCK_SUPPORT_PHYSIQUE(ID_STOCK_SUPPORT_PHYSIQUE),
  FOREIGN KEY (ID_STOCK_SUPPORT_PHYSIQUE_RECEPTEUR) REFERENCES STOCK_SUPPORT_PHYSIQUE(ID_STOCK_SUPPORT_PHYSIQUE)
  );

CREATE TABLE MAPPENG_IMMATRICULATION_BENEFICIAIRE_TMP (
  ID_BENEFICIAIRE_PHYSIQUE INTEGER NULL,
  NEW_IMATTRICULATION TEXT NULL
  );

CREATE TABLE MATRICULE_ALPHABET_TMP (
  INDEXLETTER SMALLINT NULL,
  VALUELETTER TEXT NULL
  );

CREATE TABLE MATRICULE_ATTRIBUE_TMP (
  MATRICULE7 TEXT NULL,
  MATRICULE1 TEXT NULL
  );

CREATE TABLE MATRICULE_INDEX_ROW_TMP (
  MATRICULE TEXT NULL,
  INDEXLETTER INTEGER NULL,
  ROWNUMBER INTEGER NULL
  );

CREATE TABLE MATRICULE_NON_ATTRIBUE_TMP (
  MATRICULE TEXT NULL,
  DISPONIBLE BIT NULL
  );

CREATE TABLE MENTION (
  ID_MENTION INTEGER NOT NULL,
  CODE_MENTION TEXT NULL,
  LIBELLE_MENTION TEXT NOT NULL,
  TEXTE_MENTION TEXT NOT NULL
  );

CREATE TABLE MENTION_PAR_TAMPON (
  ID_MENTION_PAR_TAMPON INTEGER NOT NULL,
  ID_TAMPON INTEGER NOT NULL,
  ID_MENTION INTEGER NOT NULL,
  NO_ORDRE INTEGER NOT NULL,
  SAUT_LIGNE BIT NOT NULL,
  FOREIGN KEY (ID_MENTION) REFERENCES MENTION(ID_MENTION),
  FOREIGN KEY (ID_TAMPON) REFERENCES TAMPON(ID_TAMPON)
  );

CREATE TABLE MODELE_DOCUMENT (
  ID_MODELE_DOCUMENT INTEGER NOT NULL,
  ID_TYPE_CAMPAGNE INTEGER NULL,
  CODE_MODELE_DOCUMENT TEXT NULL,
  LIBELLE_MODELE_DOCUMENT TEXT NOT NULL,
  URL_MODELE_DOCUMENT TEXT NULL,
  EST_CAMPAGNE BIT NOT NULL,
  EST_IMPERSONNEL BIT NOT NULL,
  FOREIGN KEY (ID_TYPE_CAMPAGNE) REFERENCES TYPE_CAMPAGNE(ID_TYPE_CAMPAGNE)
  );

CREATE TABLE MOTIF_DELIVRANCE (
  ID_MOTIF_DELIVRANCE INTEGER NOT NULL,
  CODE_MOTIF_DELIVRANCE TEXT NULL,
  LIBELLE_MOTIF_DELIVRANCE TEXT NOT NULL
  );

CREATE TABLE MOTIF_DEMANDE (
  ID_MOTIF_DEMANDE INTEGER NOT NULL,
  CODE_MOTIF_DEMANDE TEXT NULL,
  LIBELLE_MOTIF_DEMANDE TEXT NOT NULL
  );

CREATE TABLE MOTIF_REJET (
  ID_MOTIF_REJET INTEGER NOT NULL,
  CODE_MOTIF_REJET TEXT NULL,
  LIBELLE_MOTIF_REJET TEXT NOT NULL
  );

CREATE TABLE MOTIF_STATUT (
  ID_MOTIF_STATUT INTEGER NOT NULL,
  ID_STATUT_FACILITE INTEGER NOT NULL,
  CODE_MOTIF_STATUT TEXT NULL,
  LIBELLE_MOTIF_STATUT TEXT NOT NULL,
  FOREIGN KEY (ID_STATUT_FACILITE) REFERENCES STATUT_FACILITE(ID_STATUT_FACILITE)
  );

CREATE TABLE MOUVEMENT_STOCK (
  ID_MOUVEMENT_STOCK INTEGER NOT NULL,
  ID_STOCK_SUPPORT_PHYSIQUE INTEGER NOT NULL,
  ID_TYPE_MOUVEMENT INTEGER NOT NULL,
  NOMBRE_MVT INTEGER NOT NULL,
  DATE_MVT REAL NOT NULL,
  FOREIGN KEY (ID_STOCK_SUPPORT_PHYSIQUE) REFERENCES STOCK_SUPPORT_PHYSIQUE(ID_STOCK_SUPPORT_PHYSIQUE),
  FOREIGN KEY (ID_TYPE_MOUVEMENT) REFERENCES TYPE_MOUVEMENT(ID_TYPE_MOUVEMENT)
  );

CREATE TABLE ODTRATTACHE (
  ID_ODTRATTACHE INTEGER NOT NULL,
  ID_FILIATION INTEGER NOT NULL,
  EST_ODTVAT BIT NOT NULL,
  ID_ADT INTEGER NOT NULL,
  ID_ODT INTEGER NOT NULL,
  FOREIGN KEY (ID_ADT) REFERENCES BENEFICIAIRE_PHYSIQUE(ID_BENEFICIAIRE_PHYSIQUE),
  FOREIGN KEY (ID_FILIATION) REFERENCES FILIATION(ID_FILIATION),
  FOREIGN KEY (ID_ODT) REFERENCES BENEFICIAIRE_PHYSIQUE(ID_BENEFICIAIRE_PHYSIQUE)
  );

CREATE TABLE PARAMETRAGE_PROPRE_UTILISATEUR (
  ID_PARAMETRAGE_PROPRE_UTILISATEUR INTEGER NOT NULL,
  ID_PARAMETRE_UTILISATEUR INTEGER NOT NULL,
  ID_UTILISATEUR INTEGER NOT NULL,
  VALEUR TEXT NOT NULL,
  FOREIGN KEY (ID_PARAMETRE_UTILISATEUR) REFERENCES PARAMETRE_UTILISATEUR(ID_PARAMETRE_UTILISATEUR),
  FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
  );

CREATE TABLE PARAMETRE (
  ID_PARAMETRE INTEGER NOT NULL,
  CODE_PARAMETRE TEXT NULL,
  LIBELLE_PARAMETRE TEXT NOT NULL,
  VALEUR_PARAMETRE TEXT NULL
  );

CREATE TABLE PARAMETRE_UTILISATEUR (
  ID_PARAMETRE_UTILISATEUR INTEGER NOT NULL,
  CODE_PARAMETRE_UTILISATEUR TEXT NULL,
  LIBELLE_PARAMETRE_UTILISATEUR TEXT NOT NULL
  );

CREATE TABLE PARCOURS_DEMANDE (
  ID_PARCOURS_DEMANDE INTEGER NOT NULL,
  ID_GARE_DESTINATION INTEGER NOT NULL,
  ID_GARE_ORIGINE INTEGER NOT NULL,
  ID_GARE_VIA INTEGER NULL,
  ID_DOSSIER_DELIVRANCE INTEGER NULL,
  ID_DEMANDE INTEGER NULL,
  ID_TYPE_TRAJET INTEGER NOT NULL,
  NOMBRE_ACCOMPAGNANTS_ADULTES INTEGER NULL,
  NOMBRE_ACCOMPAGNANTS_ENFANTS INTEGER NULL,
  FOREIGN KEY (ID_DEMANDE) REFERENCES DEMANDE(ID_DEMANDE),
  FOREIGN KEY (ID_DOSSIER_DELIVRANCE) REFERENCES DOSSIER_DELIVRANCE(ID_DOSSIER_DELIVRANCE),
  FOREIGN KEY (ID_GARE_DESTINATION) REFERENCES GARE(ID_GARE),
  FOREIGN KEY (ID_GARE_ORIGINE) REFERENCES GARE(ID_GARE),
  FOREIGN KEY (ID_GARE_VIA) REFERENCES GARE(ID_GARE),
  FOREIGN KEY (ID_TYPE_TRAJET) REFERENCES TYPE_TRAJET(ID_TYPE_TRAJET)
  );

CREATE TABLE PERIMETRE_GESTION (
  ID_UTILISATEUR INTEGER NOT NULL,
  ID_SOUS_CATEGORIE_BENEFICIAIRE INTEGER NOT NULL,
  FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR),
  FOREIGN KEY (ID_SOUS_CATEGORIE_BENEFICIAIRE) REFERENCES SOUS_CATEGORIE_BENEFICIAIRE(ID_SOUS_CATEGORIE_BENEFICIAIRE)
  );

CREATE TABLE PERIMETRE_LIEU_AFFECTATION (
  ID_UTILISATEUR INTEGER NOT NULL,
  ID_LIEU_AFFECTATION INTEGER NOT NULL,
  FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR),
  FOREIGN KEY (ID_LIEU_AFFECTATION) REFERENCES LIEU_AFFECTATION(ID_LIEU_AFFECTATION)
  );

CREATE TABLE PERMISSION (
  ID_PERMISSION INTEGER NOT NULL,
  CODE_PERMISSION TEXT NULL,
  LIBELLE_PERMISSION TEXT NULL,
  DESCRIPTION TEXT NULL
  );

CREATE TABLE PERMISSION_PAR_PROFIL (
  ID_PERMISSION INTEGER NOT NULL,
  ID_PROFIL INTEGER NOT NULL,
  FOREIGN KEY (ID_PROFIL) REFERENCES PROFIL(ID_PROFIL),
  FOREIGN KEY (ID_PERMISSION) REFERENCES PERMISSION(ID_PERMISSION)
  );

CREATE TABLE PIECE_JOINTE (
  ID_PIECE_JOINTE INTEGER NOT NULL,
  ID_BENEFICIAIRE INTEGER NULL,
  ID_FACILITE INTEGER NULL,
  ID_TYPE_EXTENSION INTEGER NOT NULL,
  LIBELLE_PIECE_JOINTE TEXT NULL,
  URL_PIECE_JOINTE_LOCAL TEXT NULL,
  ID_GED TEXT NULL,
  EST_PHOTO BIT NOT NULL,
  EST_SPECIMEN BIT NOT NULL,
  EST_AENVOYE_EN_GED BIT NOT NULL,
  EST_APURGER BIT NOT NULL,
  EN_PRE_CREATION BIT NOT NULL,
  CHEMIN_PIECE_JOINTE_LOCAL TEXT NULL,
  FOREIGN KEY (ID_BENEFICIAIRE) REFERENCES BENEFICIAIRE(ID_BENEFICIAIRE),
  FOREIGN KEY (ID_FACILITE) REFERENCES FACILITE(ID_FACILITE),
  FOREIGN KEY (ID_TYPE_EXTENSION) REFERENCES TYPE_EXTENSION(ID_TYPE_EXTENSION)
  );

CREATE TABLE PIECE_JOINTE_TMP (
  ID_PIECE_JOINTE_TMP INTEGER NOT NULL,
  CODE_PIECE_JOINTE_TMP TEXT NULL,
  URL_PIECE_JOINTE_TMP TEXT NULL,
  DATE_CREATION REAL NULL
  );

CREATE TABLE PJDEMANDE (
  ID_PJDEMANDE INTEGER NOT NULL,
  ID_BENEFICIAIRE INTEGER NULL,
  ID_PIECE_JOINTE INTEGER NOT NULL,
  ID_DEMANDE INTEGER NOT NULL,
  DATE_AJOUT_ALA_DEMANDE REAL NOT NULL,
  FOREIGN KEY (ID_BENEFICIAIRE) REFERENCES BENEFICIAIRE(ID_BENEFICIAIRE),
  FOREIGN KEY (ID_DEMANDE) REFERENCES DEMANDE(ID_DEMANDE),
  FOREIGN KEY (ID_PIECE_JOINTE) REFERENCES PIECE_JOINTE(ID_PIECE_JOINTE)
  );

CREATE TABLE PLANIFICATION (
  ID_PLANIFICATION INTEGER NOT NULL,
  CODE_PLANIFICATION TEXT NULL
  );

CREATE TABLE PROFIL (
  ID_PROFIL INTEGER NOT NULL,
  CODE_PROFIL TEXT NULL,
  LIBELLE_PROFIL TEXT NOT NULL
  );

CREATE TABLE PROPOSITION_BNF_RNVLMT (
  ID_PROPOSITION_BNF_RNVLMT INTEGER NOT NULL,
  ID_BENEFICIAIRE INTEGER NOT NULL,
  ID_RENOUVELEMENT_FC INTEGER NOT NULL,
  ID_MOTIF_REJET INTEGER NULL,
  DATE_TRAITEMENT REAL NOT NULL,
  LIBELLE_EXCLUSION TEXT NULL,
  ID_STATUT_RENOUVELEMENT INTEGER NOT NULL,
  FOREIGN KEY (ID_BENEFICIAIRE) REFERENCES BENEFICIAIRE(ID_BENEFICIAIRE),
  FOREIGN KEY (ID_MOTIF_REJET) REFERENCES MOTIF_REJET(ID_MOTIF_REJET),
  FOREIGN KEY (ID_RENOUVELEMENT_FC) REFERENCES RENOUVELEMENT_FC(ID_RENOUVELEMENT_FC),
  FOREIGN KEY (ID_STATUT_RENOUVELEMENT) REFERENCES STATUT_RENOUVELEMENT(ID_STATUT_RENOUVELEMENT)
  );

CREATE TABLE PROPOSITION_CAT_BNF_MOD_DOC (
  ID_MODELE_DOCUMENT INTEGER NOT NULL,
  ID_CATEGORIE_BENEFICIAIRE INTEGER NOT NULL,
  FOREIGN KEY (ID_MODELE_DOCUMENT) REFERENCES MODELE_DOCUMENT(ID_MODELE_DOCUMENT),
  FOREIGN KEY (ID_CATEGORIE_BENEFICIAIRE) REFERENCES CATEGORIE_BENEFICIAIRE(ID_CATEGORIE_BENEFICIAIRE)
  );

CREATE TABLE PROPOSITION_CAT_BNF_TXT_REF (
  ID_CATEGORIE_BENEFICIAIRE INTEGER NOT NULL,
  ID_TEXTE_REFERENCE INTEGER NOT NULL,
  FOREIGN KEY (ID_TEXTE_REFERENCE) REFERENCES TEXTE_REFERENCE(ID_TEXTE_REFERENCE),
  FOREIGN KEY (ID_CATEGORIE_BENEFICIAIRE) REFERENCES CATEGORIE_BENEFICIAIRE(ID_CATEGORIE_BENEFICIAIRE)
  );

CREATE TABLE PROPOSITION_CODE_FACILITE_CODE_TARIF (
  ID_CODE_FACILITE INTEGER NOT NULL,
  ID_CODE_TARIF INTEGER NOT NULL,
  FOREIGN KEY (ID_CODE_FACILITE) REFERENCES CODE_FACILITE(ID_CODE_FACILITE),
  FOREIGN KEY (ID_CODE_TARIF) REFERENCES CODE_TARIF(ID_CODE_TARIF)
  );

CREATE TABLE PROPOSITION_CODE_FACILITE_TARIFICATION (
  ID_TARIFICATION INTEGER NOT NULL,
  ID_CODE_FACILITE INTEGER NOT NULL,
  FOREIGN KEY (ID_TARIFICATION) REFERENCES TARIFICATION(ID_TARIFICATION),
  FOREIGN KEY (ID_CODE_FACILITE) REFERENCES CODE_FACILITE(ID_CODE_FACILITE)
  );

CREATE TABLE PROPOSITION_FCRNVLMT (
  ID_PROPOSITION_FCRNVLMT INTEGER NOT NULL,
  ID_DOSSIER_DELIVRANCE INTEGER NULL,
  ID_CLASSE_VOITURE INTEGER NULL,
  ID_SOUS_CATEGORIE_BENEFICIAIRE INTEGER NOT NULL,
  ID_PROPOSITION_BNF_RNVLMT INTEGER NOT NULL,
  ID_CODE_FACILITE INTEGER NOT NULL,
  DATE_DEBUT_VALIDITE REAL NULL,
  DATE_FIN_VALIDITE REAL NULL,
  MILLESIME TEXT NULL,
  NB_CASE_OU_DPR INTEGER NULL,
  MENTION1 TEXT NULL,
  MENTION2 TEXT NULL,
  MENTION3 TEXT NULL,
  MENTION4 TEXT NULL,
  MENTION5 TEXT NULL,
  MENTION6 TEXT NULL,
  MENTION7 TEXT NULL,
  MENTION8 TEXT NULL,
  MENTION9 TEXT NULL,
  MENTION10 TEXT NULL,
  ID_STATUT_RENOUVELEMENT INTEGER NULL,
  FOREIGN KEY (ID_CLASSE_VOITURE) REFERENCES CLASSE_VOITURE(ID_CLASSE_VOITURE),
  FOREIGN KEY (ID_CODE_FACILITE) REFERENCES CODE_FACILITE(ID_CODE_FACILITE),
  FOREIGN KEY (ID_DOSSIER_DELIVRANCE) REFERENCES DOSSIER_DELIVRANCE(ID_DOSSIER_DELIVRANCE),
  FOREIGN KEY (ID_PROPOSITION_BNF_RNVLMT) REFERENCES PROPOSITION_BNF_RNVLMT(ID_PROPOSITION_BNF_RNVLMT),
  FOREIGN KEY (ID_SOUS_CATEGORIE_BENEFICIAIRE) REFERENCES SOUS_CATEGORIE_BENEFICIAIRE(ID_SOUS_CATEGORIE_BENEFICIAIRE),
  FOREIGN KEY (ID_STATUT_RENOUVELEMENT) REFERENCES STATUT_RENOUVELEMENT(ID_STATUT_RENOUVELEMENT)
  );

CREATE TABLE PROPOSITION_TYPE_SUPPORT_PHYSIQUE (
  ID_CODE_FACILITE INTEGER NOT NULL,
  ID_TYPE_SUPPORT_PHYSIQUE INTEGER NOT NULL,
  FOREIGN KEY (ID_TYPE_SUPPORT_PHYSIQUE) REFERENCES TYPE_SUPPORT_PHYSIQUE(ID_TYPE_SUPPORT_PHYSIQUE),
  FOREIGN KEY (ID_CODE_FACILITE) REFERENCES CODE_FACILITE(ID_CODE_FACILITE)
  );

CREATE TABLE RATTACHEMENT_SS_CAT_ABENEFICIAIRE (
  ID_RATTACHEMENT_SS_CAT_ABENEFICIAIRE INTEGER NOT NULL,
  ID_SOUS_CATEGORIE_BENEFICIAIRE INTEGER NOT NULL,
  ID_BENEFICIAIRE INTEGER NOT NULL,
  DATE_DEBUT_DROIT REAL NULL,
  DATE_FIN_DROIT REAL NULL,
  ID_FILIATION INTEGER NOT NULL,
  FOREIGN KEY (ID_BENEFICIAIRE) REFERENCES BENEFICIAIRE(ID_BENEFICIAIRE),
  FOREIGN KEY (ID_FILIATION) REFERENCES FILIATION(ID_FILIATION),
  FOREIGN KEY (ID_SOUS_CATEGORIE_BENEFICIAIRE) REFERENCES SOUS_CATEGORIE_BENEFICIAIRE(ID_SOUS_CATEGORIE_BENEFICIAIRE)
  );

CREATE TABLE REASSORT (
  ID_REASSORT INTEGER NOT NULL,
  NUMERO_DEBUT TEXT NOT NULL,
  NUMERO_FIN TEXT NOT NULL,
  DATE_CREATION_REASSORT REAL NOT NULL,
  ID_STOCK_SUPPORT_PHYSIQUE INTEGER NOT NULL,
  FOREIGN KEY (ID_STOCK_SUPPORT_PHYSIQUE) REFERENCES STOCK_SUPPORT_PHYSIQUE(ID_STOCK_SUPPORT_PHYSIQUE)
  );

CREATE TABLE REGION_DELIVRANCE (
  ID_DOSSIER_DELIVRANCE INTEGER NOT NULL,
  ID_REGION_FC INTEGER NOT NULL,
  FOREIGN KEY (ID_REGION_FC) REFERENCES REGION_FC(ID_REGION_FC),
  FOREIGN KEY (ID_DOSSIER_DELIVRANCE) REFERENCES DOSSIER_DELIVRANCE(ID_DOSSIER_DELIVRANCE)
  );

CREATE TABLE REGION_FC (
  ID_REGION_FC INTEGER NOT NULL,
  CODE_REGION_FC TEXT NULL,
  LIBELLE_REGION_FC TEXT NOT NULL
  );

CREATE TABLE RENOUVELEMENT_FC (
  ID_RENOUVELEMENT_FC INTEGER NOT NULL,
  MILLESIME TEXT NULL,
  DATE_CALCUL REAL NULL
  );

CREATE TABLE RESPONSABILITE_GESTION (
  ID_RESPONSABILITE_GESTION INTEGER NOT NULL,
  CODE_RG TEXT NULL,
  STATUT TEXT NULL,
  LIBELLE_LONG_RG TEXT NULL,
  LIBELLE_COURT_RG TEXT NULL,
  ID_AXE_CENTRAL_PAR_DEFAUT INTEGER NULL,
  FOREIGN KEY (ID_AXE_CENTRAL_PAR_DEFAUT) REFERENCES AXE_CENTRAL(ID_AXE_CENTRAL)
  );

CREATE TABLE RESPONSABILITE_GESTION_BUGL (
  ID_BUGL INTEGER NOT NULL,
  ID_RESPONSABILITE_GESTION INTEGER NOT NULL,
  FOREIGN KEY (ID_BUGL) REFERENCES BUGL(ID_BUGL),
  FOREIGN KEY (ID_RESPONSABILITE_GESTION) REFERENCES RESPONSABILITE_GESTION(ID_RESPONSABILITE_GESTION)
  );

CREATE TABLE RETOUR_INVALIDATION_CARTE_WS (
  ID_RETOUR_INVALIDATION_CARTE_WS INTEGER NOT NULL,
  CODE_INVALIDATION_CARTE TEXT NOT NULL,
  LIBELLE_INVALIDATION_CARTE TEXT NULL
  );

CREATE TABLE SITUATION_FAMILIALE (
  ID_SITUATION_FAMILIALE INTEGER NOT NULL,
  ID_TYPE_SITUATION INTEGER NOT NULL,
  DATE_SITUATION_FAMILIALE REAL NULL,
  FOREIGN KEY (ID_TYPE_SITUATION) REFERENCES TYPE_SITUATION(ID_TYPE_SITUATION)
  );

CREATE TABLE SOUS_CATEGORIE_BENEFICIAIRE (
  ID_SOUS_CATEGORIE_BENEFICIAIRE INTEGER NOT NULL,
  ID_CATEGORIE_BENEFICIAIRE INTEGER NOT NULL,
  ID_TYPE_SOUS_CATEGORIE INTEGER NOT NULL,
  CODE_SOUS_CATEGORIE_BENEFICIAIRE TEXT NULL,
  LIBELLE_SOUS_CATEGORIE_BENEFICIAIRE TEXT NOT NULL,
  EST_AUTORISEE_AYANT_DROIT BIT NOT NULL,
  AUTORISE_VALIDATION_MASSIVE BIT NOT NULL,
  NB_KZ_ADT INTEGER NULL,
  NB_KZ_ODT INTEGER NULL,
  EST_SUPPRESSION_LOGIQUE BIT NOT NULL,
  FOREIGN KEY (ID_CATEGORIE_BENEFICIAIRE) REFERENCES CATEGORIE_BENEFICIAIRE(ID_CATEGORIE_BENEFICIAIRE),
  FOREIGN KEY (ID_TYPE_SOUS_CATEGORIE) REFERENCES TYPE_SOUS_CATEGORIE(ID_TYPE_SOUS_CATEGORIE)
  );

CREATE TABLE SS_CAT_BNF_CODE_FACILITE (
  ID_SS_CAT_BNF_CODE_FACILITE INTEGER NOT NULL,
  ID_CODE_TARIF INTEGER NULL,
  ID_CODE_FACILITE INTEGER NOT NULL,
  ID_SOUS_CATEGORIE_BENEFICIAIRE INTEGER NULL,
  FOREIGN KEY (ID_CODE_FACILITE) REFERENCES CODE_FACILITE(ID_CODE_FACILITE),
  FOREIGN KEY (ID_CODE_TARIF) REFERENCES CODE_TARIF(ID_CODE_TARIF),
  FOREIGN KEY (ID_SOUS_CATEGORIE_BENEFICIAIRE) REFERENCES SOUS_CATEGORIE_BENEFICIAIRE(ID_SOUS_CATEGORIE_BENEFICIAIRE)
  );

CREATE TABLE SS_CAT_BNF_TYPE_FACILITE (
  ID_SS_CAT_BNF_TYPE_FACILITE INTEGER NOT NULL,
  ID_SOUS_CATEGORIE_BENEFICIAIRE INTEGER NOT NULL,
  ID_TYPE_FACILITE INTEGER NOT NULL,
  CONTINGENCE INTEGER NOT NULL,
  FOREIGN KEY (ID_SOUS_CATEGORIE_BENEFICIAIRE) REFERENCES SOUS_CATEGORIE_BENEFICIAIRE(ID_SOUS_CATEGORIE_BENEFICIAIRE),
  FOREIGN KEY (ID_TYPE_FACILITE) REFERENCES TYPE_FACILITE(ID_TYPE_FACILITE)
  );

CREATE TABLE STATUT_CARTE_APUCE (
  ID_STATUT_CARTE_APUCE INTEGER NOT NULL,
  CODE_STATUT_CARTE_APUCE TEXT NULL,
  LIBELLE_ETAT_CARTE_APUCE TEXT NOT NULL
  );

CREATE TABLE STATUT_DEMANDE (
  ID_STATUT_DEMANDE INTEGER NOT NULL,
  CODE_STATUT_DEMANDE TEXT NULL,
  LIBELLE_STATUT_DEMANDE TEXT NOT NULL
  );

CREATE TABLE STATUT_FACILITE (
  ID_STATUT_FACILITE INTEGER NOT NULL,
  CODE_STATUT_FACILITE TEXT NULL,
  LIBELLE_STATUT_FACILITE TEXT NOT NULL
  );

CREATE TABLE STATUT_RENOUVELEMENT (
  ID_STATUT_RENOUVELEMENT INTEGER NOT NULL,
  CODE_STATUT_RENOUVELEMENT TEXT NOT NULL,
  LIBELLE_STATUT_RENOUVELEMENT TEXT NOT NULL
  );

CREATE TABLE STATUT_TRAITEMENT (
  ID_STATUT_TRAITEMENT INTEGER NOT NULL,
  STATUT_TRAITEMENT TEXT NOT NULL,
  LIBELLE_STATUT_TRAITEMENT TEXT NOT NULL
  );

CREATE TABLE STOCK_SUPPORT_PHYSIQUE (
  ID_STOCK_SUPPORT_PHYSIQUE INTEGER NOT NULL,
  ID_TYPE_SUPPORT_PHYSIQUE INTEGER NOT NULL,
  ID_LIEU_AFFECTATION INTEGER NOT NULL,
  SEUIL_ALERTE INTEGER NULL,
  DATE_CREATION_STOCK REAL NULL,
  FOREIGN KEY (ID_LIEU_AFFECTATION) REFERENCES LIEU_AFFECTATION(ID_LIEU_AFFECTATION),
  FOREIGN KEY (ID_TYPE_SUPPORT_PHYSIQUE) REFERENCES TYPE_SUPPORT_PHYSIQUE(ID_TYPE_SUPPORT_PHYSIQUE)
  );

CREATE TABLE SUPPORT_OPERATION (
  ID_SUPPORT_OPERATION INTEGER NOT NULL,
  CODE_SUPPORT_OPERATION TEXT NULL,
  LIBELLE_LONG_SUPPORT_OPERATION TEXT NULL,
  LIBELLE_COURT_SUPPORT_OPERATION TEXT NULL,
  STATUT TEXT NULL
  );

CREATE TABLE SUPPORT_OPERATION_BUGL (
  ID_BUGL INTEGER NOT NULL,
  ID_SUPPORT_OPERATION INTEGER NOT NULL,
  FOREIGN KEY (ID_SUPPORT_OPERATION) REFERENCES SUPPORT_OPERATION(ID_SUPPORT_OPERATION),
  FOREIGN KEY (ID_BUGL) REFERENCES BUGL(ID_BUGL)
  );

CREATE TABLE SUSPENSION_BNF (
  ID_SUSPENSION_BNF INTEGER NOT NULL,
  DATE_DEBUT_SUSPENSION REAL NULL,
  DATE_FIN_SUSPENSION REAL NULL,
  LIBELLE_MOTIF_SUSPENSION TEXT NULL
  );

CREATE TABLE TACHE (
  ID_TACHE INTEGER NOT NULL,
  ID_TYPE_TACHE INTEGER NOT NULL,
  ID_APPLICATION_ENTREE INTEGER NULL,
  ID_APPLICATION_SORTIE INTEGER NULL,
  ID_PLANIFICATION INTEGER NULL,
  CODE_TACHE TEXT NULL,
  LIBELLE_TACHE TEXT NOT NULL,
  FOREIGN KEY (ID_APPLICATION_ENTREE) REFERENCES APPLICATION(ID_APPLICATION),
  FOREIGN KEY (ID_APPLICATION_SORTIE) REFERENCES APPLICATION(ID_APPLICATION),
  FOREIGN KEY (ID_PLANIFICATION) REFERENCES PLANIFICATION(ID_PLANIFICATION),
  FOREIGN KEY (ID_TYPE_TACHE) REFERENCES TYPE_TACHE(ID_TYPE_TACHE)
  );

CREATE TABLE TAMPON (
  ID_TAMPON INTEGER NOT NULL,
  ID_TYPE_TAMPON INTEGER NOT NULL,
  CODE_TAMPON TEXT NULL,
  LIBELLE_TAMPON TEXT NOT NULL,
  EST_SUPPRESSION_LOGIQUE BIT NOT NULL,
  FOREIGN KEY (ID_TYPE_TAMPON) REFERENCES TYPE_TAMPON(ID_TYPE_TAMPON)
  );

CREATE TABLE TAMPON_PAR_CODE_FC (
  ID_TAMPON INTEGER NOT NULL,
  ID_CODE_FACILITE INTEGER NOT NULL,
  FOREIGN KEY (ID_CODE_FACILITE) REFERENCES CODE_FACILITE(ID_CODE_FACILITE)
  );

CREATE TABLE TARIFICATION (
  ID_TARIFICATION INTEGER NOT NULL,
  EST_LOCAL BIT NOT NULL,
  EST_MODIFIE BIT NOT NULL,
  CODE_TARIFICATION TEXT NULL,
  DATE_DEBUT_VALIDITE REAL NULL,
  DATE_FIN_VALIDITE REAL NULL,
  ID_TYPE_BAREME INTEGER NOT NULL,
  ID_CLASSE_VOITURE INTEGER NULL,
  ID_TYPE_TARIFICATION INTEGER NOT NULL,
  EST_TARIFICATION_IDF BIT NULL,
  FOREIGN KEY (ID_CLASSE_VOITURE) REFERENCES CLASSE_VOITURE(ID_CLASSE_VOITURE),
  FOREIGN KEY (ID_TYPE_BAREME) REFERENCES TYPE_BAREME(ID_TYPE_BAREME),
  FOREIGN KEY (ID_TYPE_TARIFICATION) REFERENCES TYPE_TARIFICATION(ID_TYPE_TARIFICATION)
  );

CREATE TABLE TARIFICATION_DETAILLEE (
  ID_TARIFICATION_DETAILLEE INTEGER NOT NULL,
  DISTANCE_DEBUT INTEGER NULL,
  DISTANCE_FIN INTEGER NULL,
  COEFFICIENT_A NUMERIC(9, 4) NOT NULL,
  COEFFICIENT_B NUMERIC(9, 4) NULL,
  EST_TARIFICATION_FORFAIT BIT NOT NULL,
  ID_TARIFICATION INTEGER NOT NULL,
  FOREIGN KEY (ID_TARIFICATION) REFERENCES TARIFICATION(ID_TARIFICATION)
  );

CREATE TABLE TEXTE_REFERENCE (
  ID_TEXTE_REFERENCE INTEGER NOT NULL,
  IDENTIFIANT_GED TEXT NULL,
  LIBELLE TEXT NULL,
  URL_SYSPRE TEXT NULL,
  ID_TYPE_EXTENSION INTEGER NULL,
  FOREIGN KEY (ID_TYPE_EXTENSION) REFERENCES TYPE_EXTENSION(ID_TYPE_EXTENSION)
  );

CREATE TABLE TMP_BAREME_SVSI (
  ID_TMP_BAREME_SVSI INTEGER NOT NULL,
  CODE_BAREME TEXT NOT NULL,
  ID_TYPE_BAREME INTEGER NULL,
  ID_CLASSE INTEGER NULL,
  DISTANCE_DEBUT INTEGER NULL,
  DISTANCE_FIN INTEGER NULL,
  PARAMETRE_A NUMERIC(9, 4) NULL,
  PARAMETRE_B NUMERIC(9, 4) NULL,
  ID_TYPE_TARIFICATION INTEGER NULL,
  DATE_DEBUT_VALIDITE REAL NULL,
  DATE_FIN_VALIDITE REAL NULL
  );

CREATE TABLE TMP_CORRESPONDANCE_SS_CAT_BNF_FCT1_FCT2 (
  ID_TMP_CORRESPONDANCE_SS_CAT_BNF_FCT1_FC INTEGER NOT NULL,
  CODE_SS_CAT_BNF_FCT1 TEXT NOT NULL,
  CODE_SS_CAT_BNF_FCT2 TEXT NOT NULL,
  ID_SS_CAT_BNF_FCT2 INTEGER NULL
  );

CREATE TABLE TMP_REF_CDG_AC_DEFAUT (
  ID_TMP_REF_CDG_AC_DEFAUT INTEGER NOT NULL,
  CODE_RG TEXT NULL,
  CODE_AXE_CENTRAL TEXT NULL,
  CODE_AXE_LOCAL TEXT NULL,
  CODE_SUPPORT_OPERATION TEXT NULL,
  ENTITE_PC TEXT NULL,
  CODE_PROJET TEXT NULL,
  ACTIVITE_PROJET TEXT NULL,
  CODE_ACTIVITE TEXT NULL,
  STATUT TEXT NULL
  );

CREATE TABLE TRAITEMENT_FICHIER (
  ID_TRAITEMENT_FICHIER INTEGER NOT NULL,
  ID_EXECUTION_TACHE INTEGER NOT NULL,
  ID_ETAT_FICHIER INTEGER NOT NULL,
  ID_TYPE_FICHIER INTEGER NOT NULL,
  URL_EMPLACEMENT_FICHIER TEXT NULL,
  DATE_DEBUT_TRAITEMENT REAL NULL,
  DATE_FIN_TRAITEMENT REAL NULL,
  FOREIGN KEY (ID_ETAT_FICHIER) REFERENCES ETAT_FICHIER(ID_ETAT_FICHIER),
  FOREIGN KEY (ID_EXECUTION_TACHE) REFERENCES EXECUTION_TACHE(ID_EXECUTION_TACHE),
  FOREIGN KEY (ID_TYPE_FICHIER) REFERENCES TYPE_FICHIER(ID_TYPE_FICHIER)
  );

CREATE TABLE TYPE_APPEL_WS (
  ID_TYPE_APPEL_WS INTEGER NOT NULL,
  LIBELLE_TYPE_APPEL_WS TEXT NULL
  );

CREATE TABLE TYPE_BAREME (
  ID_TYPE_BAREME INTEGER NOT NULL,
  CODE_TYPE_BAREME TEXT NULL,
  LIBELLE_TYPE_BAREME TEXT NOT NULL,
  EST_MENSUEL BIT NOT NULL
  );

CREATE TABLE TYPE_CAMPAGNE (
  ID_TYPE_CAMPAGNE INTEGER NOT NULL,
  CODE_TYPE_CAMPAGNE TEXT NULL,
  LIBELLE_TYPE_CAMPAGNE TEXT NOT NULL
  );

CREATE TABLE TYPE_DEMANDE (
  ID_TYPE_DEMANDE INTEGER NOT NULL,
  CODE_TYPE_DEMANDE TEXT NULL,
  LIBELLE_TYPE_DEMANDE TEXT NOT NULL
  );

CREATE TABLE TYPE_ERREUR_FICHIER (
  ID_TYPE_ERREUR_FICHIER INTEGER NOT NULL,
  CODE_TYPE_ERREUR_FICHIER TEXT NULL,
  LIBELLE_TYPE_ERREUR_FICHIER TEXT NOT NULL
  );

CREATE TABLE TYPE_ERREUR_TACHE (
  ID_TYPE_ERREUR_TACHE INTEGER NOT NULL,
  CODE_TYPE_ERREUR TEXT NULL,
  LIBELLE_TYPE_ERREUR TEXT NOT NULL
  );

CREATE TABLE TYPE_EVENEMENT (
  ID_TYPE_EVENEMENT INTEGER NOT NULL,
  CODE_TYPE_EVENEMENT TEXT NULL,
  LIBELLE_TYPE_EVENEMENT TEXT NOT NULL
  );

CREATE TABLE TYPE_EXTENSION (
  ID_TYPE_EXTENSION INTEGER NOT NULL,
  CODE_TYPE_EXTENSION TEXT NULL,
  LIBELLE_TYPE_EXTENSION TEXT NOT NULL
  );

CREATE TABLE TYPE_FACILITE (
  ID_TYPE_FACILITE INTEGER NOT NULL,
  CODE_TYPE_FACILITE TEXT NULL,
  LIBELLE_TYPE_FACILITE TEXT NOT NULL,
  EST_FRANCE_ENTIERE BIT NOT NULL,
  EST_EDITABLE BIT NOT NULL
  );

CREATE TABLE TYPE_FICHIER (
  ID_TYPE_FICHIER INTEGER NOT NULL,
  CODE_TYPE_FICHIER TEXT NULL,
  LIBELLE_TYPE_FICHIER TEXT NOT NULL
  );

CREATE TABLE TYPE_FILIATION (
  ID_TYPE_FILIATION INTEGER NOT NULL,
  CODE_TYPE_FILIATION TEXT NULL,
  LIBELLE_TYPE_FILIATION TEXT NOT NULL
  );

CREATE TABLE TYPE_GARE (
  ID_TYPE_GARE INTEGER NOT NULL,
  CODE_TYPE_GARE TEXT NULL,
  LIBELLE_TYPE_GARE TEXT NOT NULL
  );

CREATE TABLE TYPE_LIEU_AFFECTATION (
  ID_TYPE_LIEU_AFFECTATION INTEGER NOT NULL,
  CODE_TYPE_LIEU_AFFECTATION TEXT NULL,
  LIBELLE_TYPE_LIEU_AFFECTATION TEXT NULL
  );

CREATE TABLE TYPE_LIVRAISON (
  ID_TYPE_LIVRAISON INTEGER NOT NULL,
  CODE_TYPE_LIVRAISON TEXT NULL,
  LIBELLE_TYPE_LIVRAISON TEXT NOT NULL
  );

CREATE TABLE TYPE_MOUVEMENT (
  ID_TYPE_MOUVEMENT INTEGER NOT NULL,
  LIBELLE_TYPE_MVT TEXT NOT NULL,
  CODE_TYPE_MOUVEMENT TEXT NULL
  );

CREATE TABLE TYPE_SITUATION (
  ID_TYPE_SITUATION INTEGER NOT NULL,
  CODE_TYPE_SITUATION TEXT NULL,
  LIBELLE_TYPE_SITUATION TEXT NOT NULL
  );

CREATE TABLE TYPE_SOUS_CATEGORIE (
  ID_TYPE_SOUS_CATEGORIE INTEGER NOT NULL,
  CODE_TYPE_SOUS_CATEGORIE TEXT NULL,
  LIBELLE_TYPE_SOUS_CATEGORIE TEXT NOT NULL
  );

CREATE TABLE TYPE_SUPPORT_PHYSIQUE (
  ID_TYPE_SUPPORT_PHYSIQUE INTEGER NOT NULL,
  CODE_TYPE_SUPPORT_PHYSIQUE TEXT NULL,
  LIBELLE_TYPE_SUPPORT_PHYSIQUE TEXT NOT NULL,
  NB_TYPE_SUPPORT_FC INTEGER NOT NULL
  );

CREATE TABLE TYPE_TACHE (
  ID_TYPE_TACHE INTEGER NOT NULL,
  CODE_TYPE_TACHE TEXT NULL,
  LIBELLE_TYPE_TACHE TEXT NOT NULL
  );

CREATE TABLE TYPE_TAMPON (
  ID_TYPE_TAMPON INTEGER NOT NULL,
  CODE_TYPE_TAMPON TEXT NULL,
  LIBELLE_TYPE_TAMPON TEXT NOT NULL
  );

CREATE TABLE TYPE_TARIFICATION (
  ID_TYPE_TARIFICATION INTEGER NOT NULL,
  CODE_TYPE_TARIFICATION TEXT NULL,
  LIBELLE_TYPE_TARIFICATION TEXT NOT NULL
  );

CREATE TABLE TYPE_TRAJET (
  ID_TYPE_TRAJET INTEGER NOT NULL,
  CODE_TYPE_TRAJET TEXT NULL,
  LIBELLE_TYPE_TRAJET TEXT NOT NULL
  );

CREATE TABLE TYPE_VALORISATION (
  ID_TYPE_VALORISATION INTEGER NOT NULL,
  CODE_TYPE_VALORISATION TEXT NULL,
  LIBELLE_TYPE_VALORISATION TEXT NOT NULL
  );

CREATE TABLE UNITE_OEUVRE (
  ID_UNITE_OEUVRE INTEGER NOT NULL,
  ID_AXE_CENTRAL INTEGER NOT NULL,
  ID_SUPPORT_OPERATION INTEGER NOT NULL,
  CODE_UNITE_OEUVRE TEXT NULL,
  LIBELLE_UNITE_OEUVRE TEXT NOT NULL,
  VALEUR_UNITE_OEUVRE NUMERIC(4, 2) NULL,
  ID_TYPE_SUPPORT_PHYSIQUE INTEGER NULL,
  FOREIGN KEY (ID_AXE_CENTRAL) REFERENCES AXE_CENTRAL(ID_AXE_CENTRAL),
  FOREIGN KEY (ID_SUPPORT_OPERATION) REFERENCES SUPPORT_OPERATION(ID_SUPPORT_OPERATION),
  FOREIGN KEY (ID_TYPE_SUPPORT_PHYSIQUE) REFERENCES TYPE_SUPPORT_PHYSIQUE(ID_TYPE_SUPPORT_PHYSIQUE)
  );

CREATE TABLE UTILISATEUR (
  ID_UTILISATEUR INTEGER NOT NULL,
  ID_PROFIL INTEGER NULL,
  ID_BUGL INTEGER NOT NULL,
  CODE_IMMATRICULATION TEXT NULL,
  NOM TEXT NOT NULL,
  PRENOM TEXT NOT NULL,
  EMAIL TEXT NULL,
  TELEPHONE TEXT NULL,
  DATE_DEBUT_VALIDITE REAL NOT NULL,
  DATE_FIN_VALIDITE REAL NULL,
  ID_LIEU_AFFECTATION_PAR_DEFAUT INTEGER NULL,
  ID_DEPARTEMENT INTEGER NULL,
  DATE_DERNIERE_CONNEXION REAL NULL,
  DATE_ACCEPTATION_CGU REAL NULL,
  FOREIGN KEY (ID_BUGL) REFERENCES BUGL(ID_BUGL),
  FOREIGN KEY (ID_DEPARTEMENT) REFERENCES DEPARTEMENT(ID_DEPARTEMENT),
  FOREIGN KEY (ID_LIEU_AFFECTATION_PAR_DEFAUT) REFERENCES LIEU_AFFECTATION(ID_LIEU_AFFECTATION),
  FOREIGN KEY (ID_PROFIL) REFERENCES PROFIL(ID_PROFIL)
  );

CREATE TABLE WS_BOUCHON (
  ID_WS_BOUCHON INTEGER NOT NULL,
  ID_TYPE_APPEL_WS INTEGER NULL,
  ID_APPEL_WS INTEGER NULL,
  JSON_DATA TEXT NULL
  );

