--simple-ddl-parser ne comprends pas les " WITH CHECK" donc il faut les enlever

USE [servicecarmillon]
GO
/****** Object:  Table [dbo].[T_AGENCE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_AGENCE](
	[PK_AGENCE_AGC] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_AGC] [varchar](5) NOT NULL,
	[TX_LIBELLE_AGC] [varchar](30) NULL,
 CONSTRAINT [PK_T_AGENCE] PRIMARY KEY CLUSTERED
(
	[PK_AGENCE_AGC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_TX_CODE_AGC_T_AGENCE] UNIQUE NONCLUSTERED
(
	[TX_CODE_AGC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_APPLICATION_SATELLITE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_APPLICATION_SATELLITE](
	[PK_APPLICATION_SATELLITE_ASA] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_ASA] [varchar](10) NOT NULL,
	[TX_LIBELLE_ASA] [varchar](30) NULL,
 CONSTRAINT [PK_T_APPLICATION_SATELLITE] PRIMARY KEY CLUSTERED
(
	[PK_APPLICATION_SATELLITE_ASA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_TX_CODE_ASA_T_APPLIC] UNIQUE NONCLUSTERED
(
	[TX_CODE_ASA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_BENEFICIAIRE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_BENEFICIAIRE](
	[PK_BENEFICIAIRE_BNF] [int] IDENTITY(1,1) NOT NULL,
	[FK_CATEGORIE_BENEFICIAIRE_CTB] [int] NOT NULL,
	[FK_COMMUNE_CMN] [int] NULL,
	[FK_TYPE_BENEFICAIRE_TYB] [int] NOT NULL,
	[FK_AGENCE_AGC] [int] NOT NULL,
	[FK_ETABLISSEMENT_REFERENCE_ETB] [int] NULL,
	[FK_GRADE_GRD] [int] NULL,
	[TX_CODE_IMMAT_BNF] [varchar](8) NOT NULL,
	[TX_NOM_BNF] [varchar](28) NULL,
	[TX_PRENOM_BNF] [varchar](18) NULL,
	[TX_CIVILITE_BNF] [varchar](4) NULL,
	[TX_ADRESSE_RUE_BNF] [varchar](150) NULL,
	[TX_ADRESSE_COMPLEMENT_BNF] [varchar](60) NULL,
	[TX_ADRESSE_CODE_POSTAL_BNF] [varchar](16) NULL,
	[TX_ADRESSE_COMMUNE_BNF] [varchar](50) NULL,
	[TX_ADRESSE_PAYS_BNF] [varchar](50) NULL,
	[TX_TEL_PERSO_BNF] [varchar](10) NULL,
	[TX_MAIL_PERSO_BNF] [varchar](384) NULL,
	[NM_SOLDE_DPR_AN_COUR_BNF] [int] NULL,
	[NM_SOLDE_DPR_AN_SUIV_BNF] [int] NULL,
	[DT_DATE_DERNIERE_MAJ_BNF] [datetime] NULL,
	[IM_PHOTO_BNF] [image] NULL,
	[DT_DATE_DEPOT_PHOTO_BNF] [datetime] NULL,
	[DT_DATE_SUPPRESSION_PHOTO_BNF] [datetime] NULL,
	[BL_A_ENVOYER_SIV_BNF] [bit] NULL,
	[BL_DOTATION_ANNUELLE_BNF] [bit] NULL,
	[BL_CODE_SECRET_A_ENVOYER_BNF] [bit] NULL,
	[TX_CODE_SECRET_BNF] [varchar](12) NULL,
	[DT_DATE_DERNIER_ENVOI_CODE_SECRET_BNF] [datetime] NULL,
	[TX_QUALIFICATION_BNF] [varchar](2) NULL,
	[TX_NIVEAU_BNF] [varchar](2) NULL,
	[BL_ENVOI_ADRESSE_ADMINISTRATIVE_BNF] [bit] NOT NULL,
	[TX_POSITION_BNF] [varchar](2) NULL,
	[TX_STATUT_BNF] [varchar](2) NULL,
	[BL_PILOTE_BNF] [bit] NULL,
	[TX_DATE_NAISSANCE] [datetime] NULL,
	[FK_LIEU_PRINCIPAL_AFFECTATION_LPA] [int] NULL,
	[FK_UNITE_ORGANISATIONELLE_UO] [int] NULL,
	[TX_CODE_SOCIETE_BNF] [varchar](3) NULL,
	[BL_MEDECIN_TEMPS_COMPLET_BNF] [bit] NULL,
 CONSTRAINT [PK_T_BENEFICIAIRE] PRIMARY KEY CLUSTERED
(
	[PK_BENEFICIAIRE_BNF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_BENEFICIAIRE] ADD  DEFAULT ((0)) FOR [BL_MEDECIN_TEMPS_COMPLET_BNF]
GO
ALTER TABLE [dbo].[T_BENEFICIAIRE]  WITH CHECK ADD  CONSTRAINT [FK_T_BENEFI_FK_BENEFI_T_CATEGO] FOREIGN KEY([FK_CATEGORIE_BENEFICIAIRE_CTB])
REFERENCES [dbo].[T_CATEGORIE_BENEFICIAIRE] ([PK_CATEGORIE_BENEFICIAIRE_CTB])
GO
ALTER TABLE [dbo].[T_BENEFICIAIRE]  WITH CHECK ADD  CONSTRAINT [FK_T_BENEFI_FK_BENEFI_T_TYPE_B] FOREIGN KEY([FK_TYPE_BENEFICAIRE_TYB])
REFERENCES [dbo].[T_TYPE_BENEFICAIRE] ([PK_TYPE_BENEFICIAIRE_TYB])
GO
ALTER TABLE [dbo].[T_BENEFICIAIRE]  WITH CHECK ADD  CONSTRAINT [FK_T_BENEFI_FK_COMMUN_T_COMMUN] FOREIGN KEY([FK_COMMUNE_CMN])
REFERENCES [dbo].[T_COMMUNE] ([PK_COMMUNE_CMN])
GO
ALTER TABLE [dbo].[T_BENEFICIAIRE]  WITH CHECK ADD  CONSTRAINT [FK_T_BENEFI_FK_ETABLI_T_ETABLI] FOREIGN KEY([FK_ETABLISSEMENT_REFERENCE_ETB])
REFERENCES [dbo].[T_ETABLISSEMENT_REFERENCE] ([PK_ETABLISSEMENT_REFERENCE_ETB])
GO
ALTER TABLE [dbo].[T_BENEFICIAIRE]  WITH CHECK ADD  CONSTRAINT [FK_T_BENEFI_FK_GRADE__T_GRADE] FOREIGN KEY([FK_GRADE_GRD])
REFERENCES [dbo].[T_GRADE] ([PK_GRADE_GRD])
GO
ALTER TABLE [dbo].[T_BENEFICIAIRE]  WITH CHECK ADD  CONSTRAINT [FK_T_BENEFI_FK_T_BENE_T_AGENCE] FOREIGN KEY([FK_AGENCE_AGC])
REFERENCES [dbo].[T_AGENCE] ([PK_AGENCE_AGC])
GO
ALTER TABLE [dbo].[T_BENEFICIAIRE]  WITH CHECK ADD  CONSTRAINT [FK_T_BENEFICIAIRE_T_LPA] FOREIGN KEY([FK_LIEU_PRINCIPAL_AFFECTATION_LPA])
REFERENCES [dbo].[T_LPA] ([PK_LIEU_PRINCIPAL_AFFECTATION_LPA])
GO
ALTER TABLE [dbo].[T_BENEFICIAIRE]  WITH CHECK ADD  CONSTRAINT [FK_T_BENEFICIAIRE_T_UO] FOREIGN KEY([FK_UNITE_ORGANISATIONELLE_UO])
REFERENCES [dbo].[T_UO] ([PK_UNITE_ORGANISATIONNELLE_UO])
GO
/****** Object:  Table [dbo].[T_BUG_DOMICILE_TRAVAIL_RETRAITES]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_BUG_DOMICILE_TRAVAIL_RETRAITES](
	[DT_DATE_TRAITEMENT_DTR] [datetime] NOT NULL,
	[TX_CODE_IMMAT_DTR] [varchar](8) NOT NULL,
	[FK_GARE_ORIGINE_GAR] [int] NULL,
	[FK_GARE_DESTINATION_GAR] [int] NULL,
	[DT_DATE_DEB_VALIDITE_DOMTRA_DRT] [datetime] NULL,
	[DT_DATE_FIN_VALIDITE_DOMTRA_DRT] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_CARTE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_CARTE](
	[PK_CARTE_CRT] [int] IDENTITY(1,1) NOT NULL,
	[FK_ETAT_CARTE_ETC] [int] NOT NULL,
	[FK_GARE_DESTINATION_GAR] [int] NULL,
	[FK_BENEFICIAIRE_BNF] [int] NULL,
	[FK_GARE_ORIGINE_GAR] [int] NULL,
	[TX_NUM_SERIE_CRT] [varchar](20) NOT NULL,
	[TX_NOM_CRT] [varchar](28) NULL,
	[TX_PRENOM_CRT] [varchar](18) NULL,
	[DT_DATE_DEPOT_DEMANDE_CRT] [datetime] NULL,
	[DT_DATE_DEB_VALIDITE_CRT] [datetime] NULL,
	[DT_DATE_FIN_VALIDITE_CRT] [datetime] NULL,
	[DT_DATE_DELIVRANCE_CRT] [datetime] NULL,
	[DT_DATE_FIN_LC_CRT] [datetime] NULL,
	[BL_CODE_PIN_ACTIF_CRT] [bit] NULL,
	[TX_CODE_RESEAU_CRT] [varchar](10) NULL,
	[TX_CLASSE_CRT] [varchar](2) NULL,
	[TX_CODE_IMMAT_ACCOMPAGNANT_CRT] [varchar](8) NULL,
	[BL_SURCLASSEMENT_IDF_CRT] [bit] NULL,
	[BL_SURCLASSEMENT_HORS_IDF_CRT] [bit] NULL,
	[DT_DATE_FIN_VALIDITE_DOMTRA_CRT] [datetime] NULL,
	[BL_MAITRE_CHIEN_CRT] [bit] NULL,
	[BL_CANIF_CRT] [bit] NULL,
	[BL_A_ENVOYER_SIV_CRT] [bit] NULL,
	[TX_CODE_IMMAT_GESTIONNAIRE_CRT] [varchar](8) NULL,
	[TX_CODE_CATEGORIE_CRT] [varchar](2) NULL,
	[DT_DATE_ETAT_COURANT_CRT] [datetime] NULL,
	[NM_CODE1000_CRT] [int] NULL,
 CONSTRAINT [PK_T_CARTE] PRIMARY KEY CLUSTERED
(
	[PK_CARTE_CRT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_CARTE]  WITH CHECK ADD  CONSTRAINT [FK_T_CARTE_EST_ACTUE_T_ETAT_C] FOREIGN KEY([FK_ETAT_CARTE_ETC])
REFERENCES [dbo].[T_ETAT_CARTE] ([PK_ETAT_CARTE_ETC])
GO
ALTER TABLE [dbo].[T_CARTE]  WITH CHECK ADD  CONSTRAINT [FK_T_CARTE_FK_GARE_O_T_GARE] FOREIGN KEY([FK_GARE_ORIGINE_GAR])
REFERENCES [dbo].[T_GARE] ([PK_GARE_GAR])
GO
ALTER TABLE [dbo].[T_CARTE]  WITH CHECK ADD  CONSTRAINT [FK_T_CARTE_FK_GARE_T_T_GARE] FOREIGN KEY([FK_GARE_DESTINATION_GAR])
REFERENCES [dbo].[T_GARE] ([PK_GARE_GAR])
GO
ALTER TABLE [dbo].[T_CARTE]  WITH CHECK ADD  CONSTRAINT [FK_T_CARTE_POSSEDE_T_BENEFI] FOREIGN KEY([FK_BENEFICIAIRE_BNF])
REFERENCES [dbo].[T_BENEFICIAIRE] ([PK_BENEFICIAIRE_BNF])
GO
/****** Object:  Table [dbo].[T_CARTE_PASSTRAIN]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_CARTE_PASSTRAIN](
	[PK_CARTE_PASSTRAIN_CRT] [int] IDENTITY(1,1) NOT NULL,
	[FK_ETAT_CARTE_PASSTRAIN_ETC] [int] NOT NULL,
	[FK_GARE_DESTINATION_GAR] [int] NULL,
	[FK_BENEFICIAIRE_BNF] [int] NULL,
	[FK_GARE_ORIGINE_GAR] [int] NULL,
	[TX_NUM_SERIE_CRT] [varchar](20) NOT NULL,
	[TX_NOM_CRT] [varchar](28) NULL,
	[TX_PRENOM_CRT] [varchar](18) NULL,
	[DT_DATE_DEPOT_DEMANDE_CRT] [datetime] NULL,
	[DT_DATE_DEB_VALIDITE_CRT] [datetime] NULL,
	[DT_DATE_FIN_VALIDITE_CRT] [datetime] NULL,
	[DT_DATE_DELIVRANCE_CRT] [datetime] NULL,
	[DT_DATE_FIN_LC_CRT] [datetime] NULL,
	[BL_CODE_PIN_ACTIF_CRT] [bit] NULL,
	[TX_CODE_RESEAU_CRT] [varchar](10) NULL,
	[TX_CLASSE_CRT] [varchar](2) NULL,
	[TX_CODE_IMMAT_ACCOMPAGNANT_CRT] [varchar](8) NULL,
	[BL_SURCLASSEMENT_IDF_CRT] [bit] NULL,
	[BL_SURCLASSEMENT_HORS_IDF_CRT] [bit] NULL,
	[DT_DATE_FIN_VALIDITE_DOMTRA_CRT] [datetime] NULL,
	[BL_MAITRE_CHIEN_CRT] [bit] NULL,
	[BL_CANIF_CRT] [bit] NULL,
	[BL_A_ENVOYER_SIV_CRT] [bit] NULL,
	[TX_CODE_IMMAT_GESTIONNAIRE_CRT] [varchar](8) NULL,
	[TX_CODE_CATEGORIE_CRT] [varchar](2) NULL,
	[DT_DATE_ETAT_COURANT_CRT] [datetime] NULL,
	[NM_CODE1000_CRT] [int] NULL,
 CONSTRAINT [PK_T_CARTE_PASSTRAIN] PRIMARY KEY CLUSTERED
(
	[PK_CARTE_PASSTRAIN_CRT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_CARTE_PASSTRAIN]  WITH CHECK ADD  CONSTRAINT [FK_T_CARTE_PASSTRAIN_EST_ACTUE_T_ETAT_C] FOREIGN KEY([FK_ETAT_CARTE_PASSTRAIN_ETC])
REFERENCES [dbo].[T_ETAT_CARTE_PASSTRAIN] ([PK_ETAT_CARTE_PASSTRAIN_ETC])
GO
ALTER TABLE [dbo].[T_CARTE_PASSTRAIN]  WITH CHECK ADD  CONSTRAINT [FK_T_CARTE_PASSTRAIN_FK_GARE_O_T_GARE] FOREIGN KEY([FK_GARE_ORIGINE_GAR])
REFERENCES [dbo].[T_GARE] ([PK_GARE_GAR])
GO
ALTER TABLE [dbo].[T_CARTE_PASSTRAIN]  WITH CHECK ADD  CONSTRAINT [FK_T_CARTE_PASSTRAIN_FK_GARE_T_T_GARE] FOREIGN KEY([FK_GARE_DESTINATION_GAR])
REFERENCES [dbo].[T_GARE] ([PK_GARE_GAR])
GO
ALTER TABLE [dbo].[T_CARTE_PASSTRAIN]  WITH CHECK ADD  CONSTRAINT [FK_T_CARTE_PASSTRAIN_POSSEDE_T_BENEFI] FOREIGN KEY([FK_BENEFICIAIRE_BNF])
REFERENCES [dbo].[T_BENEFICIAIRE] ([PK_BENEFICIAIRE_BNF])
GO
/****** Object:  Table [dbo].[T_CATEGORIE_BENEFICIAIRE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_CATEGORIE_BENEFICIAIRE](
	[PK_CATEGORIE_BENEFICIAIRE_CTB] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_CTB] [varchar](2) NOT NULL,
	[TX_LIBELLE_CTB] [varchar](30) NULL,
 CONSTRAINT [PK_T_CATEGORIE_BENEFICIAIRE] PRIMARY KEY CLUSTERED
(
	[PK_CATEGORIE_BENEFICIAIRE_CTB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_TX_CODE_CTB_T_CATEGO] UNIQUE NONCLUSTERED
(
	[TX_CODE_CTB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_COMMUNE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_COMMUNE](
	[PK_COMMUNE_CMN] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_CMN] [char](5) NULL,
	[TX_LIBELLE_CMN] [varchar](32) NULL,
 CONSTRAINT [PK_T_COMMUNE] PRIMARY KEY CLUSTERED
(
	[PK_COMMUNE_CMN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_DROITS]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_DROITS](
	[PK_DROITS_DRT] [int] IDENTITY(1,1) NOT NULL,
	[FK_GARE_ORIGINE_GAR] [int] NULL,
	[FK_GARE_DESTINATION_GAR] [int] NULL,
	[FK_BENEFICIAIRE_BNF] [int] NOT NULL,
	[BL_DELEGATION_DRT] [bit] NULL,
	[TX_CODE_IMMAT_DELEGATION1_DRT] [varchar](8) NULL,
	[TX_CODE_IMMAT_DELEGATION2_DRT] [varchar](8) NULL,
	[TX_CLASSE_DRT] [varchar](2) NULL,
	[TX_CODE_RESEAU_DRT] [varchar](10) NULL,
	[TX_CODE_IMMAT_ACCOMPAGNANT_DRT] [varchar](8) NULL,
	[BL_SURCLASSEMENT_IDF_DRT] [bit] NULL,
	[BL_SURCLASSEMENT_HORS_IDF_DRT] [bit] NULL,
	[TX_IMMAT_VOITURE_DRT] [varchar](13) NULL,
	[BL_MAITRE_CHIEN_DRT] [bit] NULL,
	[BL_TRANSILIEN_DRT] [bit] NULL,
	[BL_CANIF_DRT] [bit] NULL,
	[DT_DATE_DEB_LC_DRT] [datetime] NULL,
	[DT_DATE_FIN_LC_DRT] [datetime] NULL,
	[DT_DATE_DEB_VALIDITE_DOMTRA_DRT] [datetime] NULL,
	[DT_DATE_FIN_VALIDITE_DOMTRA_DRT] [datetime] NULL,
	[DT_DATE_DEB_SUSPENSION_LC_DRT] [datetime] NULL,
	[DT_DATE_FIN_SUSPENSION_LC_DRT] [datetime] NULL,
	[DT_DATE_DERNIERE_MAJ_DRT] [datetime] NULL,
	[BL_A_ENVOYER_SIV_DRT] [bit] NULL,
	[NM_CODE1000_DRT] [int] NULL,
 CONSTRAINT [PK_T_DROITS] PRIMARY KEY CLUSTERED
(
	[PK_DROITS_DRT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_DROITS]  WITH CHECK ADD  CONSTRAINT [FK_T_DROITS_CONCERNEN_T_BENEFI] FOREIGN KEY([FK_BENEFICIAIRE_BNF])
REFERENCES [dbo].[T_BENEFICIAIRE] ([PK_BENEFICIAIRE_BNF])
GO
ALTER TABLE [dbo].[T_DROITS]  WITH CHECK ADD  CONSTRAINT [FK_T_DROITS_FK_GARE_D_T_GARE] FOREIGN KEY([FK_GARE_DESTINATION_GAR])
REFERENCES [dbo].[T_GARE] ([PK_GARE_GAR])
GO
ALTER TABLE [dbo].[T_DROITS]  WITH CHECK ADD  CONSTRAINT [FK_T_DROITS_FK_GARE_O_T_GARE] FOREIGN KEY([FK_GARE_ORIGINE_GAR])
REFERENCES [dbo].[T_GARE] ([PK_GARE_GAR])
GO
/****** Object:  Table [dbo].[T_ETABLISSEMENT_REFERENCE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_ETABLISSEMENT_REFERENCE](
	[PK_ETABLISSEMENT_REFERENCE_ETB] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_ETB] [varchar](6) NOT NULL,
	[TX_LIBELLE_ETB] [varchar](30) NULL,
	[TX_CODE_REGION_ETB] [varchar](2) NULL,
 CONSTRAINT [PK_T_ETABLISSEMENT_REFERENCE] PRIMARY KEY CLUSTERED
(
	[PK_ETABLISSEMENT_REFERENCE_ETB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_TX_CODE_ETB_T_ETABLI] UNIQUE NONCLUSTERED
(
	[TX_CODE_ETB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_ETAT_CARTE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_ETAT_CARTE](
	[PK_ETAT_CARTE_ETC] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_ETC] [varchar](1) NOT NULL,
	[TX_LIBELLE_ETC] [varchar](30) NULL,
 CONSTRAINT [PK_T_ETAT_CARTE] PRIMARY KEY CLUSTERED
(
	[PK_ETAT_CARTE_ETC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_TX_CODE_ETC_T_ETAT_C] UNIQUE NONCLUSTERED
(
	[TX_CODE_ETC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_ETAT_CARTE_PASSTRAIN]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_ETAT_CARTE_PASSTRAIN](
	[PK_ETAT_CARTE_PASSTRAIN_ETC] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_ETC] [varchar](1) NOT NULL,
	[TX_LIBELLE_ETC] [varchar](30) NULL,
 CONSTRAINT [PK_T_ETAT_CARTE_PASSTRAIN] PRIMARY KEY CLUSTERED
(
	[PK_ETAT_CARTE_PASSTRAIN_ETC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_TX_CODE_ETC_T_ETAT_C_PASSTRAIN] UNIQUE NONCLUSTERED
(
	[TX_CODE_ETC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_ETAT_PERSONNALISATION]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_ETAT_PERSONNALISATION](
	[PK_ETAT_PERSONNALISATION_ETP] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_ETP] [varchar](1) NOT NULL,
	[TX_LIBELLE_ETP] [varchar](30) NULL,
 CONSTRAINT [PK_T_ETAT_PERSONNALISATION] PRIMARY KEY CLUSTERED
(
	[PK_ETAT_PERSONNALISATION_ETP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_TX_CODE_ETP_T_ETAT_P] UNIQUE NONCLUSTERED
(
	[TX_CODE_ETP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_FLUX]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_FLUX](
	[PK_FLUX_FLX] [int] IDENTITY(1,1) NOT NULL,
	[FK_APPLICATION_SATELLITE_ASA] [int] NOT NULL,
	[FK_TYPE_FLUX_TFL] [int] NOT NULL,
	[NM_NUMERO_FLX] [int] NOT NULL,
	[NM_INDEX_FLX] [int] NULL,
	[TX_CODE_FLUX_FLX] [varchar](15) NULL,
 CONSTRAINT [PK_T_FLUX] PRIMARY KEY CLUSTERED
(
	[PK_FLUX_FLX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_FLUX]  WITH CHECK ADD  CONSTRAINT [FK_T_FLUX_A_UN_TYPE_T_TYPE_F] FOREIGN KEY([FK_TYPE_FLUX_TFL])
REFERENCES [dbo].[T_TYPE_FLUX] ([PK_TYPE_FLUX_TFL])
GO
ALTER TABLE [dbo].[T_FLUX]  WITH CHECK ADD  CONSTRAINT [FK_T_FLUX_CONCERNE__T_APPLIC] FOREIGN KEY([FK_APPLICATION_SATELLITE_ASA])
REFERENCES [dbo].[T_APPLICATION_SATELLITE] ([PK_APPLICATION_SATELLITE_ASA])
GO
/****** Object:  Table [dbo].[T_FLUX_ENVOYE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_FLUX_ENVOYE](
	[PK_FLUX_ENVOYE_FEN] [int] IDENTITY(1,1) NOT NULL,
	[FK_FLUX_FLX] [int] NOT NULL,
	[DT_DATE_ENVOI_FEN] [datetime] NULL,
	[BL_ERREUR_FEN] [bit] NULL,
	[TX_LIBELLE_ERREUR_FEN] [varchar](30) NULL,
 CONSTRAINT [PK_T_FLUX_ENVOYE] PRIMARY KEY CLUSTERED
(
	[PK_FLUX_ENVOYE_FEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_FLUX_ENVOYE]  WITH CHECK ADD  CONSTRAINT [FK_T_FLUX_E_A_ETE_ENV_T_FLUX] FOREIGN KEY([FK_FLUX_FLX])
REFERENCES [dbo].[T_FLUX] ([PK_FLUX_FLX])
GO
/****** Object:  Table [dbo].[T_FLUX_ERREUR_DONNEES]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_FLUX_ERREUR_DONNEES](
	[PK_FLUX_DONNEES_FDO] [int] IDENTITY(1,1) NOT NULL,
	[FK_AGENCE_AGC] [int] NULL,
	[FK_FLUX_RECU_FRE] [int] NOT NULL,
	[TX_ORIGINE_FDO] [varchar](30) NULL,
	[TX_LIGNE_FDO] [varchar](256) NULL,
	[TX_CODE_IMMAT_BENEFICIAIRE_FDO] [varchar](8) NULL,
 CONSTRAINT [PK_T_FLUX_ERREUR_DONNEES] PRIMARY KEY CLUSTERED
(
	[PK_FLUX_DONNEES_FDO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_FLUX_ERREUR_DONNEES]  WITH CHECK ADD  CONSTRAINT [FK_T_FLUX_E_AVOIR_ANO_T_FLUX_R] FOREIGN KEY([FK_FLUX_RECU_FRE])
REFERENCES [dbo].[T_FLUX_RECU] ([PK_FLUX_RECU_FRE])
GO
ALTER TABLE [dbo].[T_FLUX_ERREUR_DONNEES]  WITH CHECK ADD  CONSTRAINT [FK_T_FLUX_E_CONCERNE__T_AGENCE] FOREIGN KEY([FK_AGENCE_AGC])
REFERENCES [dbo].[T_AGENCE] ([PK_AGENCE_AGC])
GO
/****** Object:  Table [dbo].[T_FLUX_ERREUR_FICHIER]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_FLUX_ERREUR_FICHIER](
	[PK_FLUX_FICHIER_FFI] [int] IDENTITY(1,1) NOT NULL,
	[FK_FLUX_RECU_FRE] [int] NOT NULL,
	[TX_ORIGINE_FFI] [varchar](30) NULL,
 CONSTRAINT [PK_T_FLUX_ERREUR_FICHIER] PRIMARY KEY CLUSTERED
(
	[PK_FLUX_FICHIER_FFI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_FLUX_ERREUR_FICHIER]  WITH CHECK ADD  CONSTRAINT [FK_T_FLUX_E_AVOIR_INC_T_FLUX_R] FOREIGN KEY([FK_FLUX_RECU_FRE])
REFERENCES [dbo].[T_FLUX_RECU] ([PK_FLUX_RECU_FRE])
GO
/****** Object:  Table [dbo].[T_FLUX_RECU]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_FLUX_RECU](
	[PK_FLUX_RECU_FRE] [int] IDENTITY(1,1) NOT NULL,
	[FK_FLUX_FLX] [int] NOT NULL,
	[FK_FLUX_ERREUR_FICHIER_FFI] [int] NULL,
	[DT_DATE_RECEPTION_FRE] [datetime] NULL,
	[DT_DATE_DEB_TRAITEMENT_FRE] [datetime] NULL,
	[DT_DATE_FIN_TRAITEMENT_FRE] [datetime] NULL,
	[TX_NOM_FICHIER_SERVEUR_FRE] [varchar](30) NULL,
 CONSTRAINT [PK_T_FLUX_RECU] PRIMARY KEY CLUSTERED
(
	[PK_FLUX_RECU_FRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_FLUX_RECU]  WITH CHECK ADD  CONSTRAINT [FK_T_FLUX_R_A_ETE_REC_T_FLUX] FOREIGN KEY([FK_FLUX_FLX])
REFERENCES [dbo].[T_FLUX] ([PK_FLUX_FLX])
GO
ALTER TABLE [dbo].[T_FLUX_RECU]  WITH CHECK ADD  CONSTRAINT [FK_T_FLUX_R_AVOIR_INC_T_FLUX_E] FOREIGN KEY([FK_FLUX_ERREUR_FICHIER_FFI])
REFERENCES [dbo].[T_FLUX_ERREUR_FICHIER] ([PK_FLUX_FICHIER_FFI])
GO
/****** Object:  Table [dbo].[T_GARE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_GARE](
	[PK_GARE_GAR] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_GAR] [varchar](6) NOT NULL,
	[TX_LIBELLE_GAR] [varchar](50) NULL,
	[BL_DELETED_GAR] [bit] NULL,
 CONSTRAINT [PK_T_GARE] PRIMARY KEY CLUSTERED
(
	[PK_GARE_GAR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_TX_CODE_GAR_T_GARE] UNIQUE NONCLUSTERED
(
	[TX_CODE_GAR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_GRADE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_GRADE](
	[PK_GRADE_GRD] [int] IDENTITY(1,1) NOT NULL,
	[TX_SYMBOLE_ENTREE_GRADE_GRD] [char](8) NULL,
	[TX_QUALIFICATION_GRD] [char](2) NULL,
	[TX_NIVEAU_GRD] [char](2) NULL,
 CONSTRAINT [PK_T_GRADE] PRIMARY KEY CLUSTERED
(
	[PK_GRADE_GRD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_HISTO_GESTIONNAIRE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_HISTO_GESTIONNAIRE](
	[PK_HISTO_GESTION_HTG] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_IMMAT_HTG] [varchar](8) NOT NULL,
	[TX_CODE_AGENCE_HTG] [varchar](8) NOT NULL,
PRIMARY KEY CLUSTERED
(
	[PK_HISTO_GESTION_HTG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_HISTO_OPERATION]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_HISTO_OPERATION](
	[PK_HISTO_OPER_HTO] [int] IDENTITY(1,1) NOT NULL,
	[FK_HISTO_SAM_HTO] [int] NOT NULL,
	[FK_HISTO_GESTION_HTO] [int] NULL,
	[FK_HISTO_PASS_HTO] [int] NULL,
	[TX_NOM_OPER_HTO] [varchar](255) NULL,
	[TX_APPLI_ORIGINE_HTO] [varchar](32) NULL,
	[TX_TYPE_DONNEE_HTO] [varchar](64) NULL,
	[TX_POSTE_ORIGINE_HTO] [varchar](32) NULL,
	[DT_DATE_OPER_HTO] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[PK_HISTO_OPER_HTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_HISTO_OPERATION]  WITH CHECK ADD FOREIGN KEY([FK_HISTO_GESTION_HTO])
REFERENCES [dbo].[T_HISTO_GESTIONNAIRE] ([PK_HISTO_GESTION_HTG])
GO
ALTER TABLE [dbo].[T_HISTO_OPERATION]  WITH CHECK ADD FOREIGN KEY([FK_HISTO_PASS_HTO])
REFERENCES [dbo].[T_HISTO_PASSCARMILLON] ([PK_HISTO_PASS_HTP])
GO
/****** Object:  Table [dbo].[T_HISTO_PASSCARMILLON]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_HISTO_PASSCARMILLON](
	[PK_HISTO_PASS_HTP] [int] IDENTITY(1,1) NOT NULL,
	[TX_NUM_CARTE_HTP] [varchar](20) NOT NULL,
	[TX_CODE_IMMAT_HTP] [varchar](8) NOT NULL,
PRIMARY KEY CLUSTERED
(
	[PK_HISTO_PASS_HTP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_HISTO_PASSTRAIN]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_HISTO_PASSTRAIN](
	[PK_HISTO_PASSTRAIN_HTP] [int] IDENTITY(1,1) NOT NULL,
	[TX_NUM_CARTE_HTP] [varchar](20) NOT NULL,
	[TX_CODE_IMMAT_HTP] [varchar](8) NOT NULL,
PRIMARY KEY CLUSTERED
(
	[PK_HISTO_PASSTRAIN_HTP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_HISTO_SAM]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_HISTO_SAM](
	[PK_HISTO_SAM_HTS] [int] IDENTITY(1,1) NOT NULL,
	[TX_NUM_SAM_HTS] [varchar](255) NOT NULL,
	[NM_NB_PERSO_HTS] [int] NOT NULL,
	[NM_NB_MAJ_HTS] [int] NOT NULL,
	[NM_NB_CANIF_HTS] [int] NOT NULL,
	[NM_NB_PLAFOND_HTS] [int] NOT NULL,
PRIMARY KEY CLUSTERED
(
	[PK_HISTO_SAM_HTS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_HISTO_SAM] ADD  DEFAULT ((0)) FOR [NM_NB_PERSO_HTS]
GO
ALTER TABLE [dbo].[T_HISTO_SAM] ADD  DEFAULT ((0)) FOR [NM_NB_MAJ_HTS]
GO
ALTER TABLE [dbo].[T_HISTO_SAM] ADD  DEFAULT ((0)) FOR [NM_NB_CANIF_HTS]
GO
ALTER TABLE [dbo].[T_HISTO_SAM] ADD  DEFAULT ((0)) FOR [NM_NB_PLAFOND_HTS]
GO
/****** Object:  Table [dbo].[T_HISTORIQUE_ETAT_CARTE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_HISTORIQUE_ETAT_CARTE](
	[PK_HISTO_ETAT_CARTE_HEC] [int] IDENTITY(1,1) NOT NULL,
	[FK_MOTIF_ETAT_CARTE_MEC] [int] NULL,
	[FK_CARTE_CRT] [int] NOT NULL,
	[FK_ETAT_CARTE_ETC] [int] NOT NULL,
	[FK_ORIGINE_ETAT_CARTE_OEC] [int] NULL,
	[DT_DATE_HEC] [datetime] NOT NULL,
 CONSTRAINT [PK_T_HISTORIQUE_ETAT_CARTE] PRIMARY KEY CLUSTERED
(
	[PK_HISTO_ETAT_CARTE_HEC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_HISTORIQUE_ETAT_CARTE]  WITH CHECK ADD  CONSTRAINT [FK_T_HISTOR_A_ETE_T_CARTE] FOREIGN KEY([FK_CARTE_CRT])
REFERENCES [dbo].[T_CARTE] ([PK_CARTE_CRT])
GO
ALTER TABLE [dbo].[T_HISTORIQUE_ETAT_CARTE]  WITH CHECK ADD  CONSTRAINT [FK_T_HISTOR_A_MOTIF_F_T_MOTIF_] FOREIGN KEY([FK_MOTIF_ETAT_CARTE_MEC])
REFERENCES [dbo].[T_MOTIF_ETAT_CARTE] ([PK_MOTIF_ETAT_CARTE_MEC])
GO
ALTER TABLE [dbo].[T_HISTORIQUE_ETAT_CARTE]  WITH CHECK ADD  CONSTRAINT [FK_T_HISTOR_A_ORIGINE_T_ORIGIN] FOREIGN KEY([FK_ORIGINE_ETAT_CARTE_OEC])
REFERENCES [dbo].[T_ORIGINE_ETAT_CARTE] ([PK_ORIGINE_ETAT_CARTE_OEC])
GO
ALTER TABLE [dbo].[T_HISTORIQUE_ETAT_CARTE]  WITH CHECK ADD  CONSTRAINT [FK_T_HISTOR_EST_T_ETAT_C] FOREIGN KEY([FK_ETAT_CARTE_ETC])
REFERENCES [dbo].[T_ETAT_CARTE] ([PK_ETAT_CARTE_ETC])
GO
/****** Object:  Table [dbo].[T_HISTORIQUE_ETAT_CARTE_PASSTRAIN]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_HISTORIQUE_ETAT_CARTE_PASSTRAIN](
	[PK_HISTO_ETAT_CARTE_PASSTRAIN_HEC] [int] IDENTITY(1,1) NOT NULL,
	[FK_MOTIF_ETAT_CARTE_PASSTRAIN_MEC] [int] NULL,
	[FK_CARTE_PASSTRAIN_CRT] [int] NOT NULL,
	[FK_ETAT_CARTE_PASSTRAIN_ETC] [int] NOT NULL,
	[FK_ORIGINE_ETAT_CARTE_PASSTRAIN_OEC] [int] NULL,
	[DT_DATE_HEC] [datetime] NOT NULL,
 CONSTRAINT [PK_T_HISTORIQUE_ETAT_CARTE_PASSTRAIN] PRIMARY KEY CLUSTERED
(
	[PK_HISTO_ETAT_CARTE_PASSTRAIN_HEC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_HISTORIQUE_ETAT_CARTE_PASSTRAIN]  WITH CHECK ADD  CONSTRAINT [FK_T_HISTOR_PASSTRAIN_A_ETE_T_CARTE] FOREIGN KEY([FK_CARTE_PASSTRAIN_CRT])
REFERENCES [dbo].[T_CARTE_PASSTRAIN] ([PK_CARTE_PASSTRAIN_CRT])
GO
ALTER TABLE [dbo].[T_HISTORIQUE_ETAT_CARTE_PASSTRAIN]  WITH CHECK ADD  CONSTRAINT [FK_T_HISTOR_PASSTRAIN_A_MOTIF_F_T_MOTIF_] FOREIGN KEY([FK_MOTIF_ETAT_CARTE_PASSTRAIN_MEC])
REFERENCES [dbo].[T_MOTIF_ETAT_CARTE_PASSTRAIN] ([PK_MOTIF_ETAT_CARTE_PASSTRAIN_MEC])
GO
ALTER TABLE [dbo].[T_HISTORIQUE_ETAT_CARTE_PASSTRAIN]  WITH CHECK ADD  CONSTRAINT [FK_T_HISTOR_PASSTRAIN_A_ORIGINE_T_ORIGIN] FOREIGN KEY([FK_ORIGINE_ETAT_CARTE_PASSTRAIN_OEC])
REFERENCES [dbo].[T_ORIGINE_ETAT_CARTE_PASSTRAIN] ([PK_ORIGINE_ETAT_CARTE_PASSTRAIN_OEC])
GO
ALTER TABLE [dbo].[T_HISTORIQUE_ETAT_CARTE_PASSTRAIN]  WITH CHECK ADD  CONSTRAINT [FK_T_HISTOR_PASSTRAIN_EST_T_ETAT_C] FOREIGN KEY([FK_ETAT_CARTE_PASSTRAIN_ETC])
REFERENCES [dbo].[T_ETAT_CARTE_PASSTRAIN] ([PK_ETAT_CARTE_PASSTRAIN_ETC])
GO
/****** Object:  Table [dbo].[T_LISTE_BLANCHE_SYDEF]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_LISTE_BLANCHE_SYDEF](
	[PK_LISTE_BLANCHE_SYDEF_LBS] [int] IDENTITY(1,1) NOT NULL,
	[TX_NUM_SERIE_LBS] [varchar](20) NOT NULL,
 CONSTRAINT [PK_T_LISTE_BLANCHE_SYDEF] PRIMARY KEY CLUSTERED
(
	[PK_LISTE_BLANCHE_SYDEF_LBS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_LPA]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_LPA](
	[PK_LIEU_PRINCIPAL_AFFECTATION_LPA] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_LPA] [varchar](8) NOT NULL,
	[TX_LIB_LONG_LPA] [varchar](45) NULL,
	[TX_LIB_COURT_LPA] [varchar](18) NULL,
	[TX_CODE_SOCIETE_LPA] [varchar](3) NULL,
	[TX_CODE_POINT_DISTRIB_LPA] [varchar](8) NULL,
	[TX_ADRESSE_VOIE_LPA] [varchar](50) NULL,
	[TX_ADRESSE_COMPLEMENT_LPA] [varchar](38) NULL,
	[TX_ADRESSE_CP_LPA] [varchar](5) NULL,
	[TX_ADRESSE_COMMUNE_LPA] [varchar](50) NULL,
	[TX_ADRESSE_PAYS_LPA] [varchar](3) NULL,
	[TX_LIB_ACHEMINEMENT_LPA] [varchar](32) NULL,
 CONSTRAINT [PK_T_LIEU_PRINCIPAL_AFFECTATION] PRIMARY KEY CLUSTERED
(
	[PK_LIEU_PRINCIPAL_AFFECTATION_LPA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_MISEAJOUR_PUCE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_MISEAJOUR_PUCE](
	[PK_MAJ_PUCE_MJP] [int] IDENTITY(1,1) NOT NULL,
	[FK_MOTIF_MISEAJOUR_MMJ] [int] NOT NULL,
	[FK_CARTE_CRT] [int] NOT NULL,
	[DT_DATE_DEPOT_DEMANDE_MJP] [datetime] NOT NULL,
	[DT_REALISATION_DEMANDE_MJP] [datetime] NULL,
 CONSTRAINT [PK_T_MISEAJOUR_PUCE] PRIMARY KEY CLUSTERED
(
	[PK_MAJ_PUCE_MJP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_MISEAJOUR_PUCE]  WITH CHECK ADD  CONSTRAINT [FK_T_MISEAJ_CONCERNE__T_CARTE] FOREIGN KEY([FK_CARTE_CRT])
REFERENCES [dbo].[T_CARTE] ([PK_CARTE_CRT])
GO
ALTER TABLE [dbo].[T_MISEAJOUR_PUCE]  WITH CHECK ADD  CONSTRAINT [FK_T_MISEAJ_CORRESPON_T_MOTIF_] FOREIGN KEY([FK_MOTIF_MISEAJOUR_MMJ])
REFERENCES [dbo].[T_MOTIF_MISEAJOUR] ([PK_MOTIF_MAJ_MMJ])
GO
/****** Object:  Table [dbo].[T_MISEAJOUR_PUCE_PASSTRAIN]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_MISEAJOUR_PUCE_PASSTRAIN](
	[PK_MAJ_PUCE_PASSTRAIN_MJP] [int] IDENTITY(1,1) NOT NULL,
	[FK_MOTIF_MISEAJOUR_MMJ] [int] NOT NULL,
	[FK_CARTE_PASSTRAIN_CRT] [int] NOT NULL,
	[DT_DATE_DEPOT_DEMANDE_MJP] [datetime] NOT NULL,
	[DT_REALISATION_DEMANDE_MJP] [datetime] NULL,
 CONSTRAINT [PK_T_MISEAJOUR_PUCE_PASSTRAIN] PRIMARY KEY CLUSTERED
(
	[PK_MAJ_PUCE_PASSTRAIN_MJP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_MISEAJOUR_PUCE_PASSTRAIN]  WITH CHECK ADD  CONSTRAINT [FK_T_MISEAJ_PASSTRAIN_CONCERNE__T_CARTE_PASSTRAIN] FOREIGN KEY([FK_CARTE_PASSTRAIN_CRT])
REFERENCES [dbo].[T_CARTE_PASSTRAIN] ([PK_CARTE_PASSTRAIN_CRT])
GO
ALTER TABLE [dbo].[T_MISEAJOUR_PUCE_PASSTRAIN]  WITH CHECK ADD  CONSTRAINT [FK_T_MISEAJ_PASSTRAIN_CORRESPON_T_MOTIF_] FOREIGN KEY([FK_MOTIF_MISEAJOUR_MMJ])
REFERENCES [dbo].[T_MOTIF_MISEAJOUR] ([PK_MOTIF_MAJ_MMJ])
GO
/****** Object:  Table [dbo].[T_MOTIF_ETAT_CARTE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_MOTIF_ETAT_CARTE](
	[PK_MOTIF_ETAT_CARTE_MEC] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_MEC] [varchar](1) NOT NULL,
	[TX_LIBELLE_MEC] [varchar](30) NULL,
 CONSTRAINT [PK_T_MOTIF_ETAT_CARTE] PRIMARY KEY CLUSTERED
(
	[PK_MOTIF_ETAT_CARTE_MEC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_TX_CODE_MEC_T_MOTIF_] UNIQUE NONCLUSTERED
(
	[TX_CODE_MEC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_MOTIF_ETAT_CARTE_PASSTRAIN]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_MOTIF_ETAT_CARTE_PASSTRAIN](
	[PK_MOTIF_ETAT_CARTE_PASSTRAIN_MEC] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_MEC] [varchar](1) NOT NULL,
	[TX_LIBELLE_MEC] [varchar](30) NULL,
 CONSTRAINT [PK_T_MOTIF_ETAT_CARTE_PASSTRAIN] PRIMARY KEY CLUSTERED
(
	[PK_MOTIF_ETAT_CARTE_PASSTRAIN_MEC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_TX_CODE_MEC_T_MOTIF_PASSTRAIN_] UNIQUE NONCLUSTERED
(
	[TX_CODE_MEC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_MOTIF_MISEAJOUR]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_MOTIF_MISEAJOUR](
	[PK_MOTIF_MAJ_MMJ] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_MMJ] [varchar](1) NOT NULL,
	[TX_LIBELLE_MMJ] [varchar](30) NULL,
 CONSTRAINT [PK_T_MOTIF_MISEAJOUR] PRIMARY KEY CLUSTERED
(
	[PK_MOTIF_MAJ_MMJ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_TX_CODE_MMJ_T_MOTIF_] UNIQUE NONCLUSTERED
(
	[TX_CODE_MMJ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_MOTIF_PERSONNALISATION]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_MOTIF_PERSONNALISATION](
	[PK_MOTIF_PERSONNALISATION_MPE] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_MPE] [varchar](1) NOT NULL,
	[TX_LIBELLE_MPE] [varchar](30) NULL,
 CONSTRAINT [PK_T_MOTIF_PERSONNALISATION] PRIMARY KEY CLUSTERED
(
	[PK_MOTIF_PERSONNALISATION_MPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_TX_CODE_MPE_T_MOTIF_] UNIQUE NONCLUSTERED
(
	[TX_CODE_MPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_MOUVEMENT_DPR]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_MOUVEMENT_DPR](
	[PK_MOUVEMENT_DPR_MVD] [int] IDENTITY(1,1) NOT NULL,
	[FK_TYPE_MACHINE_TYM] [int] NULL,
	[FK_BENEFICIAIRE_BNF] [int] NOT NULL,
	[FK_ORIGINE_DPR_ORI] [int] NOT NULL,
	[DT_DATE_MOUVEMENT_MVD] [datetime] NULL,
	[DT_DATE_TRAIN_MVD] [datetime] NULL,
	[NM_NB_DPR_AN_COUR_MVD] [int] NULL,
	[NM_NB_DPR_AN_SUIV_MVD] [int] NULL,
	[NM_SOLDE_AN_COUR_MVD] [int] NULL,
	[NM_SOLDE_AN_SUIV_MVD] [int] NULL,
	[TX_CERTIFICAT_MVD] [varchar](38) NULL,
	[TX_CODE_IMMAT_DELEGUE_MVD] [varchar](8) NULL,
	[TX_CODE_IMMAT_GESTIONNAIRE_MVD] [varchar](8) NULL,
	[BL_AR_FICHETS_RENDUS_OK_MVD] [bit] NOT NULL,
 CONSTRAINT [PK_T_MOUVEMENT_DPR] PRIMARY KEY CLUSTERED
(
	[PK_MOUVEMENT_DPR_MVD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_MOUVEMENT_DPR] ADD  CONSTRAINT [DF_T_MOUVEMENT_DPR_BL_AR_FICHETS_RENDUS_OK_MVD]  DEFAULT ((0)) FOR [BL_AR_FICHETS_RENDUS_OK_MVD]
GO
ALTER TABLE [dbo].[T_MOUVEMENT_DPR]  WITH NOCHECK ADD  CONSTRAINT [FK_T_MOUVEM_CORRESPON_T_ORIGIN] FOREIGN KEY([FK_ORIGINE_DPR_ORI])
REFERENCES [dbo].[T_ORIGINE_DPR] ([PK_ORIGINE_ORI])
GO
ALTER TABLE [dbo].[T_MOUVEMENT_DPR]  WITH NOCHECK ADD  CONSTRAINT [FK_T_MOUVEM_CORRESPON_T_TYPE_M] FOREIGN KEY([FK_TYPE_MACHINE_TYM])
REFERENCES [dbo].[T_TYPE_MACHINE] ([PK_TYPE_MACHINE_TYM])
GO
ALTER TABLE [dbo].[T_MOUVEMENT_DPR]  WITH NOCHECK ADD  CONSTRAINT [FK_T_MOUVEM_CUMULE_T_BENEFI] FOREIGN KEY([FK_BENEFICIAIRE_BNF])
REFERENCES [dbo].[T_BENEFICIAIRE] ([PK_BENEFICIAIRE_BNF])
GO
/****** Object:  Table [dbo].[T_MOUVEMENT_STATISTIQUE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_MOUVEMENT_STATISTIQUE](
	[PK_MOUVEMENT_STATISTIQUE_MST] [int] IDENTITY(1,1) NOT NULL,
	[FK_STATISTIQUE_STA] [int] NOT NULL,
	[NB_NOMBRE_MST] [int] NULL,
	[DT_DATE_MOIS_ANNEE_MST] [datetime] NULL,
 CONSTRAINT [PK_T_MOUVEMENT_STATISTIQUE] PRIMARY KEY CLUSTERED
(
	[PK_MOUVEMENT_STATISTIQUE_MST] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_MOUVEMENT_STATISTIQUE]  WITH CHECK ADD  CONSTRAINT [FK_T_MOUVEM_A_MVT_STA_T_STATIS] FOREIGN KEY([FK_STATISTIQUE_STA])
REFERENCES [dbo].[T_STATISTIQUE] ([PK_STATISTIQUE_STA])
GO
/****** Object:  Table [dbo].[T_ORIGINE_DPR]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_ORIGINE_DPR](
	[PK_ORIGINE_ORI] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_ORI] [varchar](1) NOT NULL,
	[TX_LIBELLE_ORI] [varchar](50) NULL,
 CONSTRAINT [PK_T_ORIGINE_DPR] PRIMARY KEY CLUSTERED
(
	[PK_ORIGINE_ORI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_TX_CODE_ORI_T_ORIGIN] UNIQUE NONCLUSTERED
(
	[TX_CODE_ORI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_ORIGINE_ETAT_CARTE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_ORIGINE_ETAT_CARTE](
	[PK_ORIGINE_ETAT_CARTE_OEC] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_OEC] [varchar](4) NOT NULL,
	[TX_LIBELLE_OEC] [varchar](30) NULL,
 CONSTRAINT [PK_T_ORIGINE_ETAT_CARTE] PRIMARY KEY CLUSTERED
(
	[PK_ORIGINE_ETAT_CARTE_OEC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_ORIGINE_ETAT_CARTE_PASSTRAIN]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_ORIGINE_ETAT_CARTE_PASSTRAIN](
	[PK_ORIGINE_ETAT_CARTE_PASSTRAIN_OEC] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_OEC] [varchar](4) NOT NULL,
	[TX_LIBELLE_OEC] [varchar](30) NULL,
 CONSTRAINT [PK_T_ORIGINE_ETAT_CARTE_PASSTRAIN] PRIMARY KEY CLUSTERED
(
	[PK_ORIGINE_ETAT_CARTE_PASSTRAIN_OEC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_PARAMETRE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_PARAMETRE](
	[PK_PARAMETRE_PRM] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_PRM] [varchar](6) NOT NULL,
	[TX_LIBELLE_PRM] [varchar](50) NULL,
	[TX_VALEUR_PRM] [varchar](500) NULL,
 CONSTRAINT [PK_T_PARAMETRE] PRIMARY KEY CLUSTERED
(
	[PK_PARAMETRE_PRM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_TX_CODE_PRM_T_PARAME] UNIQUE NONCLUSTERED
(
	[TX_CODE_PRM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_PAYS]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_PAYS](
	[TX_CODE_PAY] [varchar](3) NOT NULL,
	[TX_LIBELLE_PAY] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED
(
	[TX_CODE_PAY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_PERSONNALISATION]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_PERSONNALISATION](
	[PK_PERSONNALISATION_PRS] [int] IDENTITY(1,1) NOT NULL,
	[FK_BENEFICIAIRE_BNF] [int] NOT NULL,
	[FK_MOTIF_PERSONNALISATION_MPE] [int] NOT NULL,
	[FK_CARTE_CRT] [int] NULL,
	[FK_ETAT_PERSONNALISATION_ETP] [int] NOT NULL,
	[DT_DATE_DEPOT_DEMANDE_PRS] [datetime] NOT NULL,
	[FK_CARTE_PASSTRAIN_CRT] [bigint] NULL,
 CONSTRAINT [PK_T_PERSONNALISATION] PRIMARY KEY CLUSTERED
(
	[PK_PERSONNALISATION_PRS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[T_PERSONNALISATION]  WITH CHECK ADD  CONSTRAINT [FK_T_PERSON_CONCERNE__T_BENEFI] FOREIGN KEY([FK_BENEFICIAIRE_BNF])
REFERENCES [dbo].[T_BENEFICIAIRE] ([PK_BENEFICIAIRE_BNF])
GO
ALTER TABLE [dbo].[T_PERSONNALISATION]  WITH CHECK ADD  CONSTRAINT [FK_T_PERSON_CONCERNE__T_CARTE] FOREIGN KEY([FK_CARTE_CRT])
REFERENCES [dbo].[T_CARTE] ([PK_CARTE_CRT])
GO
ALTER TABLE [dbo].[T_PERSONNALISATION]  WITH CHECK ADD  CONSTRAINT [FK_T_PERSON_ESTETATPE_T_ETAT_P] FOREIGN KEY([FK_ETAT_PERSONNALISATION_ETP])
REFERENCES [dbo].[T_ETAT_PERSONNALISATION] ([PK_ETAT_PERSONNALISATION_ETP])
GO
ALTER TABLE [dbo].[T_PERSONNALISATION]  WITH CHECK ADD  CONSTRAINT [FK_T_PERSON_FK_PERSON_T_MOTIF_] FOREIGN KEY([FK_MOTIF_PERSONNALISATION_MPE])
REFERENCES [dbo].[T_MOTIF_PERSONNALISATION] ([PK_MOTIF_PERSONNALISATION_MPE])
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_PERSONNALISATION_EXTERNE](
	[PK_PERSO_EXT_PSE] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_IMMAT_PSE] [varchar](8) NOT NULL,
	[TX_NOM_FICHIER_PSE] [varchar](50) NULL,
	[TX_NUMERO_PSE] [int] NULL,
	[TX_CODE_ETAT_PERSO_PSE] [varchar](3) NULL,
	[TX_NOM_PSE] [varchar](28) NULL,
	[TX_PRENOM_PSE] [varchar](18) NULL,
	[DT_DATE_FIN_LC_PSE] [datetime] NULL,
	[TX_CLASSE_PSE] [varchar](2) NULL,
	[TX_CODE_CATEGORIE_PSE] [varchar](2) NULL,
	[BL_SURCLASSEMENT_IDF_PSE] [bit] NULL,
	[BL_SURCLASSEMENT_HORS_IDF_PSE] [bit] NULL,
	[TX_CODE_IMMAT_ACCOMPAGNANT_PSE] [varchar](8) NULL,
	[TX_CODE_GARE_ORIGINE_PSE] [varchar](6) NULL,
	[TX_CODE_GARE_DESTINATION_PSE] [varchar](6) NULL,
	[DT_DATE_FIN_VALIDITE_DOMTRA_PSE] [datetime] NULL,
	[BL_MAITRE_CHIEN_PSE] [bit] NULL,
	[BL_CODE_1000_PSE] [bit] NULL,
 CONSTRAINT [PK_T_PERSONNALISATION_EXTERNE] PRIMARY KEY CLUSTERED
(
	[PK_PERSO_EXT_PSE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_POINT_DISTRIBUTION]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_POINT_DISTRIBUTION](
	[PK_POINT_DISTRIBUTION_PDN] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_POINT_DISTRIB_PDN] [varchar](8) NOT NULL,
	[TX_CENTRE_TRI_PDN] [varchar](45) NULL,
 CONSTRAINT [PK_T_PK_POINT_DISTRIBUTION] PRIMARY KEY CLUSTERED
(
	[PK_POINT_DISTRIBUTION_PDN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_STATISTIQUE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_STATISTIQUE](
	[PK_STATISTIQUE_STA] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_STA] [varchar](5) NOT NULL,
	[TX_LIBELLE_STA] [varchar](100) NULL,
	[DT_DATE_DERNIERE_MAJ_STA] [datetime] NULL,
 CONSTRAINT [PK_T_STATISTIQUE] PRIMARY KEY CLUSTERED
(
	[PK_STATISTIQUE_STA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_TEMPORAIRE_BENEFICIAIRE_FLUX]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_TEMPORAIRE_BENEFICIAIRE_FLUX](
	[PK_TEMPORAIRE_BENEFICIAIRE_FLUX_TBF] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_IMMAT_TBF] [char](8) NULL,
	[DT_DATE_ARRIVEE_TBF] [datetime] NOT NULL,
	[BL_DROITS_TBF] [bit] NOT NULL,
	[BL_BENEFICIAIRE_TBF] [bit] NOT NULL,
	[TX_NOM_TBF] [varchar](28) NULL,
	[TX_PRENOM_TBF] [varchar](18) NULL,
	[TX_CIVILITE_TBF] [char](5) NULL,
	[TX_ADRESSE_RUE_TBF] [varchar](150) NULL,
	[TX_ADRESSE_COMPLEMENT_TBF] [char](60) NULL,
	[TX_ADRESSE_CODE_POSTAL_TBF] [char](16) NULL,
	[TX_ADRESSE_COMMUNE_TBF] [varchar](50) NULL,
	[TX_CODE_AGENCE_FAMILLE_TBF] [char](6) NULL,
	[TX_CODE_ETABLISSEMENT_TBF] [char](5) NULL,
	[TX_QUALIFICATION_TBF] [char](2) NULL,
	[TX_NIVEAU_TBF] [char](2) NULL,
	[TX_POSITION_TBF] [char](2) NULL,
	[TX_SYMBOLE_GRADE_TBF] [char](6) NULL,
	[TX_STATUT_TBF] [char](2) NULL,
	[TX_TYPE_AGENT_TBF] [char](1) NULL,
	[BL_ENVOI_ADRESSE_ADMINISTRATIVE] [bit] NOT NULL,
	[TX_CODE_CATEGORIE] [char](2) NULL,
	[TX_CLASSE_TBF] [char](2) NULL,
	[TX_CODE_RESEAU_TBF] [char](1) NULL,
	[TX_IMMAT_VOITURE_TBF] [char](13) NULL,
	[DT_DEB_LC_TBF] [datetime] NULL,
	[DT_FIN_LC_TBF] [datetime] NULL,
	[DT_DATE_DEB_SUSPENSION_LC_TBF] [datetime] NULL,
	[DT_DATE_FIN_SUSPENSION_LC_TBF] [datetime] NULL,
	[TX_DATE_NAISSANCE_TBF] [datetime] NULL,
	[TX_CODE_LPA_TBF] [varchar](8) NULL,
	[TX_CODE_UO_TBF] [varchar](10) NULL,
	[TX_CODE_COMMUNE_TBF] [varchar](5) NULL,
	[TX_CODE_PAYS_TBF] [varchar](3) NULL,
	[TX_CODE_SOCIETE_TBF] [varchar](3) NULL,
 CONSTRAINT [PK_T_TEMPORAIRE_BENEFICIAIRE_F] PRIMARY KEY CLUSTERED
(
	[PK_TEMPORAIRE_BENEFICIAIRE_FLUX_TBF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_TRAVAIL_BENEFICIAIRE_FLUX]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_TRAVAIL_BENEFICIAIRE_FLUX](
	[PK_TEMPORAIRE_BENEFICIAIRE_FLUX_TRF] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_TRAITEMENT_TRF] [char](1) NOT NULL,
	[TX_CODE_IMMAT_TRF] [char](8) NULL,
	[TX_NOM_TRF] [varchar](28) NULL,
	[TX_PRENOM_TRF] [varchar](18) NULL,
	[TX_CIVILITE_TRF] [char](4) NULL,
	[TX_ADRESSE_RUE_TRF] [varchar](150) NULL,
	[TX_ADRESSE_COMPLEMENT_TRF] [char](60) NULL,
	[TX_ADRESSE_CODE_POSTAL_TRF] [char](5) NULL,
	[TX_ADRESSE_COMMUNE_TRF] [varchar](50) NULL,
	[TX_CODE_CODE_POSTAL_TRF] [char](16) NULL,
	[TX_CODE_COMMUNE_TRF] [char](5) NULL,
	[TX_CODE_AGENCE_FAMILLE_TRF] [char](5) NULL,
	[TX_CODE_ETABLISSEMENT_TRF] [char](6) NULL,
	[TX_QUALIFICATION_TRF] [char](2) NULL,
	[TX_NIVEAU_TRF] [char](2) NULL,
	[TX_POSITION_TRF] [char](2) NULL,
	[TX_SYMBOLE_GRADE_TRF] [char](6) NULL,
	[TX_STATUT_TRF] [char](5) NULL,
	[TX_CODE_SERVICE_LIBRE_TRF] [char](3) NULL,
	[TX_CODE_APPARTENANCE_FILIALE_TRF] [char](2) NULL,
	[TX_CODE_CESSATION_TRF] [char](3) NULL,
	[TX_REGIME_CS_TRF] [char](2) NULL,
	[TX_CLASSE_TRF] [char](2) NULL,
	[TX_CODE_RESEAU_TRF] [char](1) NULL,
	[TX_IMMAT_VOITURE_TRF] [char](13) NULL,
	[TX_DEB_LC_TRF] [char](10) NULL,
	[TX_FIN_LC_TRF] [char](10) NULL,
	[TX_TYPE_AGENT_TBF] [char](1) NULL,
	[TX_DATE_DEBUT_ILD_TRF] [char](10) NULL,
	[TX_DATE_FIN_ILD_TRF] [char](10) NULL,
	[TX_DATE_CESSATION_TRF] [char](10) NULL,
	[TX_DATE_DEB_SUSPENSION_LC_TRF] [char](10) NULL,
	[TX_DATE_FIN_SUSPENSION_LC_TRF] [char](10) NULL,
	[TX_INDICATEUR_RETRAITE_TRF_] [char](1) NULL,
	[TX_DATE_NAISSANCE_TRF] [char](10) NULL,
	[TX_CODE_UO_TRF] [varchar](10) NULL,
	[TX_CODE_LPA_TRF] [varchar](8) NULL,
	[TX_CODE_PAYS_TRF] [varchar](3) NULL,
	[TX_CODE_SOCIETE_TRF] [varchar](3) NULL,
 CONSTRAINT [PK_T_TRAVAIL_BENEFICIAIRE_FLUX] PRIMARY KEY CLUSTERED
(
	[PK_TEMPORAIRE_BENEFICIAIRE_FLUX_TRF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_TYPE_BENEFICAIRE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_TYPE_BENEFICAIRE](
	[PK_TYPE_BENEFICIAIRE_TYB] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_TYB] [varchar](2) NOT NULL,
	[TX_LIBELLE_TYB] [varchar](30) NULL,
 CONSTRAINT [PK_T_TYPE_BENEFICAIRE] PRIMARY KEY CLUSTERED
(
	[PK_TYPE_BENEFICIAIRE_TYB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_TX_CODE_TYB_T_TYPE_B] UNIQUE NONCLUSTERED
(
	[TX_CODE_TYB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_TYPE_FLUX]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_TYPE_FLUX](
	[PK_TYPE_FLUX_TFL] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_TFL] [varchar](10) NOT NULL,
	[TX_LIBELLE_TFL] [varchar](30) NULL,
 CONSTRAINT [PK_T_TYPE_FLUX] PRIMARY KEY CLUSTERED
(
	[PK_TYPE_FLUX_TFL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_TX_CODE_TFL_T_TYPE_F] UNIQUE NONCLUSTERED
(
	[TX_CODE_TFL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_TYPE_MACHINE]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_TYPE_MACHINE](
	[PK_TYPE_MACHINE_TYM] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_TYM] [varchar](2) NOT NULL,
	[TX_LIBELLE_TYM] [varchar](50) NULL,
 CONSTRAINT [PK_T_TYPE_MACHINE] PRIMARY KEY CLUSTERED
(
	[PK_TYPE_MACHINE_TYM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_TX_CODE_TYM_T_TYPE_M] UNIQUE NONCLUSTERED
(
	[TX_CODE_TYM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_UO]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_UO](
	[PK_UNITE_ORGANISATIONNELLE_UO] [int] IDENTITY(1,1) NOT NULL,
	[TX_CODE_UO] [varchar](10) NOT NULL,
	[TX_LIB_LONG_UO] [varchar](100) NULL,
	[TX_LIB_COURT_UO] [varchar](25) NULL,
	[TX_CODE_ETABLISSEMENT_UO] [varchar](6) NULL,
	[TX_CODE_AGENCE_FAMILLE_UO] [varchar](8) NULL,
	[TX_CODE_CMGA_UO] [varchar](8) NULL,
 CONSTRAINT [PK_T_UNITE_ORGANISATIONNELLE] PRIMARY KEY CLUSTERED
(
	[PK_UNITE_ORGANISATIONNELLE_UO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WSMAILER_EMAIL]    Script Date: 5/26/2025 10:29:58 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WSMAILER_EMAIL](
	[ID_WSMAILER_EMAIL] [int] IDENTITY(1,1) NOT NULL,
	[SUJET] [varchar](600) NULL,
	[CORPS] [text] NULL,
	[PIECE_JOINTE] [varchar](600) NULL,
PRIMARY KEY CLUSTERED
(
	[ID_WSMAILER_EMAIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
